window.V6ControlPriceHistory=(function(){
  var FIRST_YEAR=2016;
  var STATE={timeMode:'all'};
  function $(id){return document.getElementById(id)}
  function ymd(d){return d.toISOString().slice(0,10)}
  function maxDate(){return window.V6LoadPriceHistoryData.maxDate()}
  function futureMaxDate(){return window.V6LoadPriceHistoryData.futureMaxDate?window.V6LoadPriceHistoryData.futureMaxDate():maxDate()}
  function minDate(){return window.V6LoadPriceHistoryData.minDate()}
  function periodDays(p){return window.V6LoadPriceHistoryData.periodDays(p)}
  function ensureYearOptions(){var y=$('price-history-year');if(!y||y.options.length)return;var now=futureMaxDate().getUTCFullYear();for(var n=now;n>=FIRST_YEAR;n--){var o=document.createElement('option');o.value=String(n);o.textContent=String(n);y.appendChild(o)}y.value=String(maxDate().getUTCFullYear())}
  function ensureStartDate(){var y=$('price-history-year'),s=$('price-history-start');if(!s)return;var selectedYear=y&&y.value?Number(y.value):maxDate().getUTCFullYear();if(!s.value||s.value.slice(0,4)!==String(selectedYear)){var start;if(selectedYear===maxDate().getUTCFullYear()){start=new Date(maxDate().getTime()-7*86400000)}else{start=new Date(Date.UTC(selectedYear,0,1,0,0,0))}s.value=ymd(start)}}
  function ensureModeTabs(){if($('price-history-time-tabs'))return;var actions=document.querySelector('#electricity-price-history-panel .price-history-actions');if(!actions)return;var tabs=document.createElement('div');tabs.id='price-history-time-tabs';tabs.className='price-history-time-tabs';tabs.innerHTML='<span>Hour filter</span><button type="button" data-mode="all" class="active">All</button><button type="button" data-mode="day">Day</button><button type="button" data-mode="night">Night</button>';actions.appendChild(tabs);tabs.addEventListener('click',function(e){var b=e.target.closest('button[data-mode]');if(!b)return;STATE.timeMode=b.getAttribute('data-mode');tabs.querySelectorAll('button').forEach(function(x){x.classList.toggle('active',x===b)});load()})}
  function currentPeriod(){var p=$('price-history-period');return p&&p.value?p.value:'7d'}
  function syncFullscreenPeriod(){var p=$('price-history-period'),fp=$('price-history-fullscreen-period-select');if(p&&fp&&fp.value!==p.value)fp.value=p.value}
  function setPeriod(value){var p=$('price-history-period');if(p)p.value=value;syncFullscreenPeriod();load()}
  function nudgePeriod(direction){var s=$('price-history-start');if(!s)return;var period=currentPeriod();var current=s.value?new Date(s.value+'T00:00:00Z'):new Date(maxDate().getTime()-7*86400000);var days=Math.max(1,Math.round(periodDays(period)));var next=new Date(current.getTime()+direction*days*86400000);if(next<minDate())next=minDate();if(next>futureMaxDate())next=futureMaxDate();s.value=ymd(next);var y=$('price-history-year');if(y)y.value=String(next.getUTCFullYear());load()}
  function attachPeriodButtons(scope){var back=$(scope+'-back'),forward=$(scope+'-forward');if(back&&!back.dataset.bound){back.dataset.bound='1';back.addEventListener('click',function(){nudgePeriod(-1)})}if(forward&&!forward.dataset.bound){forward.dataset.bound='1';forward.addEventListener('click',function(){nudgePeriod(1)})}}
  function ensurePeriodControls(){if($('price-history-period-nav'))return;var canvas=$('price-history-canvas');if(!canvas||!canvas.parentNode)return;var nav=document.createElement('div');nav.id='price-history-period-nav';nav.className='price-history-chart-nav';nav.innerHTML='<button type="button" id="price-history-period-back">◀ Previous period</button><button type="button" id="price-history-period-forward">Next period ▶</button>';canvas.parentNode.insertBefore(nav,canvas.nextSibling);attachPeriodButtons('price-history-period')}
  function bindFullscreenPeriodSelect(){var fp=$('price-history-fullscreen-period-select');if(!fp||fp.dataset.bound)return;fp.dataset.bound='1';syncFullscreenPeriod();fp.addEventListener('change',function(){setPeriod(fp.value)})}
  var pending=null;
  function debouncedLoad(){clearTimeout(pending);pending=setTimeout(load,120)}
  function load(){ensureStartDate();syncFullscreenPeriod();var s=$('price-history-start'),period=currentPeriod();var start=s&&s.value?new Date(s.value+'T00:00:00Z'):new Date(maxDate().getTime()-7*86400000);return window.V6LoadPriceHistoryData.loadWindow(start,period,STATE.timeMode).then(function(result){var meta=$('price-history-fullscreen-meta');if(meta)meta.textContent=new Date(result.start).toLocaleDateString('en-GB')+' to '+new Date(result.end).toLocaleDateString('en-GB')+' · '+(result.mode==='daily'?'daily average / baseline':'full settlement');window.V6RenderPriceChart.render(result)})}
  function openFullscreen(){var o=$('price-history-fullscreen-overlay');if(!o)return;syncFullscreenPeriod();o.classList.add('open');document.documentElement.classList.add('v5-chart-open');document.body.classList.add('v5-chart-open');attachPeriodButtons('price-history-fullscreen-period');setTimeout(function(){if(window.V6RenderPriceChart.redrawFullscreen)window.V6RenderPriceChart.redrawFullscreen()},80)}
  function closeFullscreen(){var o=$('price-history-fullscreen-overlay');if(!o)return;o.classList.remove('open');document.documentElement.classList.remove('v5-chart-open');document.body.classList.remove('v5-chart-open')}
  function attachFullscreenSwipe(){var c=$('price-history-fullscreen-canvas');if(!c||c.dataset.swipeBound)return;c.dataset.swipeBound='1';var sx=0,sy=0,active=false;c.addEventListener('touchstart',function(e){if(!e.touches||!e.touches.length)return;var t=e.touches[0];sx=t.clientX;sy=t.clientY;active=true},{passive:true});c.addEventListener('touchend',function(e){if(!active)return;active=false;var t=e.changedTouches&&e.changedTouches[0];if(!t)return;var dx=t.clientX-sx,dy=t.clientY-sy;if(Math.abs(dx)<55||Math.abs(dx)<Math.abs(dy)*1.25)return;nudgePeriod(dx<0?1:-1)},{passive:true})}
  function start(){ensureYearOptions();ensureModeTabs();ensurePeriodControls();ensureStartDate();attachPeriodButtons('price-history-fullscreen-period');attachFullscreenSwipe();bindFullscreenPeriodSelect();var btn=$('price-history-refresh'),period=$('price-history-period'),startEl=$('price-history-start'),year=$('price-history-year');if(btn)btn.addEventListener('click',load);if(period)period.addEventListener('change',function(){syncFullscreenPeriod();load()});if(startEl)startEl.addEventListener('change',load);if(year)year.addEventListener('change',function(){var s=$('price-history-start');if(s)s.value='';ensureStartDate();load()});var full=$('price-history-fullscreen-btn'),close=$('price-history-fullscreen-close');if(full)full.addEventListener('click',openFullscreen);if(close)close.addEventListener('click',closeFullscreen);window.addEventListener('resize',debouncedLoad);load()}
  return{start:start,load:load};
})();