window.V6ControlPriceHistory=(function(){
  var FIRST_YEAR=2016;
  var STATE={timeMode:'all'};
  function $(id){return document.getElementById(id)}
  function ymd(d){return d.toISOString().slice(0,10)}
  function maxDate(){return window.V6LoadPriceHistoryData.maxDate()}
  function minDate(){return window.V6LoadPriceHistoryData.minDate()}
  function totalScrollableDays(){return Math.max(1,Math.floor((maxDate()-minDate())/86400000))}
  function dateFromOffset(v){var d=new Date(minDate().getTime()+Number(v)*86400000);d.setUTCHours(0,0,0,0);return d}
  function offsetFromDate(d){return Math.max(0,Math.min(totalScrollableDays(),Math.floor((d-minDate())/86400000)))}
  function periodDays(p){return window.V6LoadPriceHistoryData.periodDays(p)}
  function ensureYearOptions(){var y=$('price-history-year');if(!y||y.options.length)return;var now=maxDate().getUTCFullYear();for(var n=now;n>=FIRST_YEAR;n--){var o=document.createElement('option');o.value=String(n);o.textContent=String(n);y.appendChild(o)}y.value=String(now)}
  function ensureStartDate(){var y=$('price-history-year'),s=$('price-history-start');if(!s)return;var selectedYear=y&&y.value?Number(y.value):maxDate().getUTCFullYear();if(!s.value||s.value.slice(0,4)!==String(selectedYear)){var start;if(selectedYear===maxDate().getUTCFullYear()){start=new Date(maxDate().getTime()-7*86400000)}else{start=new Date(Date.UTC(selectedYear,0,1,0,0,0))}s.value=ymd(start)}syncScrollerFromStart()}
  function syncScrollerFromStart(){var s=$('price-history-start'),r=$('price-history-scroll');if(!s||!r||!s.value)return;r.value=String(offsetFromDate(new Date(s.value+'T00:00:00Z')))}
  function syncStartFromScroller(){var r=$('price-history-scroll'),s=$('price-history-start'),y=$('price-history-year');if(!r||!s)return;var d=dateFromOffset(r.value);s.value=ymd(d);if(y)y.value=String(d.getUTCFullYear())}
  function ensureModeTabs(){if($('price-history-time-tabs'))return;var actions=document.querySelector('#electricity-price-history-panel .price-history-actions');if(!actions)return;var tabs=document.createElement('div');tabs.id='price-history-time-tabs';tabs.className='price-history-time-tabs';tabs.innerHTML='<span>Hour filter</span><button type="button" data-mode="all" class="active">All</button><button type="button" data-mode="day">Day</button><button type="button" data-mode="night">Night</button>';actions.appendChild(tabs);tabs.addEventListener('click',function(e){var b=e.target.closest('button[data-mode]');if(!b)return;STATE.timeMode=b.getAttribute('data-mode');tabs.querySelectorAll('button').forEach(function(x){x.classList.toggle('active',x===b)});load()})}
  function nudgeDays(direction){var s=$('price-history-start'),p=$('price-history-period');if(!s)return;var period=p&&p.value?p.value:'7d';var current=s.value?new Date(s.value+'T00:00:00Z'):new Date(maxDate().getTime()-7*86400000);var days=Math.max(1,Math.round(periodDays(period)));var next=new Date(current.getTime()+direction*days*86400000);if(next<minDate())next=minDate();if(next>maxDate())next=maxDate();s.value=ymd(next);var y=$('price-history-year');if(y)y.value=String(next.getUTCFullYear());syncScrollerFromStart();load()}
  function ensureScroller(){if($('price-history-scroll'))return;var panel=$('electricity-price-history-panel');var canvas=$('price-history-canvas');if(!panel||!canvas)return;var wrap=document.createElement('div');wrap.className='price-history-scroller';wrap.innerHTML='<div class="price-history-scroller-head"><strong>History scroller</strong><span id="price-history-scroll-label">1 day, 1 week, 1 month and 3 months use full settlement data. 6 months and longer use daily high, low and average.</span></div><div class="price-history-scroll-row"><button type="button" id="price-history-prev" aria-label="Move chart left">◀</button><input id="price-history-scroll" type="range" min="0" max="'+totalScrollableDays()+'" step="1"><button type="button" id="price-history-next" aria-label="Move chart right">▶</button></div>';canvas.parentNode.insertBefore(wrap,canvas);var chartNav=document.createElement('div');chartNav.className='price-history-chart-nav';chartNav.innerHTML='<button type="button" id="price-history-step-back">◀ Previous window</button><button type="button" id="price-history-step-forward">Next window ▶</button>';canvas.parentNode.insertBefore(chartNav,canvas.nextSibling);var r=$('price-history-scroll'),prev=$('price-history-prev'),next=$('price-history-next'),back=$('price-history-step-back'),forward=$('price-history-step-forward');if(r)r.addEventListener('input',function(){syncStartFromScroller();debouncedLoad()});if(prev)prev.addEventListener('click',function(){var rr=$('price-history-scroll');rr.value=String(Math.max(0,Number(rr.value)-1));syncStartFromScroller();load()});if(next)next.addEventListener('click',function(){var rr=$('price-history-scroll');rr.value=String(Math.min(totalScrollableDays(),Number(rr.value)+1));syncStartFromScroller();load()});if(back)back.addEventListener('click',function(){nudgeDays(-1)});if(forward)forward.addEventListener('click',function(){nudgeDays(1)})}
  var pending=null;
  function debouncedLoad(){clearTimeout(pending);pending=setTimeout(load,120)}
  function load(){ensureStartDate();var s=$('price-history-start'),p=$('price-history-period'),period=p&&p.value?p.value:'7d';var start=s&&s.value?new Date(s.value+'T00:00:00Z'):new Date(maxDate().getTime()-7*86400000);syncScrollerFromStart();return window.V6LoadPriceHistoryData.loadWindow(start,period,STATE.timeMode).then(function(result){var meta=$('price-history-fullscreen-meta');if(meta)meta.textContent=new Date(result.start).toLocaleDateString('en-GB')+' to '+new Date(result.end).toLocaleDateString('en-GB')+' · '+(result.mode==='daily'?'daily high low average':'full settlement');window.V6RenderPriceChart.render(result)})}
  function openFullscreen(){var o=$('price-history-fullscreen-overlay');if(!o)return;o.classList.add('open');document.documentElement.classList.add('v5-chart-open');document.body.classList.add('v5-chart-open');setTimeout(function(){if(window.V6RenderPriceChart.redrawFullscreen)window.V6RenderPriceChart.redrawFullscreen()},80)}
  function closeFullscreen(){var o=$('price-history-fullscreen-overlay');if(!o)return;o.classList.remove('open');document.documentElement.classList.remove('v5-chart-open');document.body.classList.remove('v5-chart-open')}
  function start(){ensureYearOptions();ensureModeTabs();ensureScroller();ensureStartDate();var btn=$('price-history-refresh'),period=$('price-history-period'),startEl=$('price-history-start'),year=$('price-history-year');if(btn)btn.addEventListener('click',load);if(period)period.addEventListener('change',load);if(startEl)startEl.addEventListener('change',function(){syncScrollerFromStart();load()});if(year)year.addEventListener('change',function(){var s=$('price-history-start');if(s)s.value='';ensureStartDate();load()});var full=$('price-history-fullscreen-btn'),close=$('price-history-fullscreen-close');if(full)full.addEventListener('click',openFullscreen);if(close)close.addEventListener('click',closeFullscreen);window.addEventListener('resize',debouncedLoad);load()}
  return{start:start,load:load};
})();