window.V6LoadPriceHistoryData=(function(){
  var cache={history:null,daily:null};
  function parseCsvLine(line){var out=[],v='',q=false;for(var i=0;i<line.length;i++){var c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){v+='"';i++}else q=!q}else if(c===','&&!q){out.push(v);v=''}else v+=c}out.push(v);return out}
  function parseCsv(text){text=(text||'').trim();if(!text)return[];var lines=text.split(/\r?\n/),head=parseCsvLine(lines[0]);return lines.slice(1).map(function(line){var cells=parseCsvLine(line),r={};head.forEach(function(h,i){r[h]=(cells[i]||'').trim()});var price=r.systemBuyPriceGBPperMWh||r.priceGBPperMWh||'';return{time:r.periodStartUTC||r.priceTimeUTC||'',price:Number(price)}}).filter(function(r){return r.time&&!isNaN(r.price)})}
  function periodDays(p){return {'12hday':0.5,'12hnight':0.5,'1d':1,'7d':7,'30d':30,'3m':92,'6m':183,'12m':366,'5y':1827,'10y':3653}[p]||7}
  function isDaily(p){return ['6m','12m','5y','10y'].indexOf(p)>=0}
  function loadAnnual(year){return fetch(window.V6LiveConfig.annualBase+year+'.csv?t='+Date.now(),{cache:'no-store'}).then(function(r){return r.ok?r.text():''}).then(parseCsv).catch(function(){return[]})}
  function years(start,end){var out=[];for(var y=start.getUTCFullYear();y<=end.getUTCFullYear();y++)out.push(y);return out}
  function loadDaily(){if(cache.daily)return cache.daily;cache.daily=fetch(window.V6LiveConfig.dailyPriceHistory+'?t='+Date.now(),{cache:'no-store'}).then(function(r){return r.ok?r.json():{rows:[]}}).then(function(d){return d.rows||[]}).catch(function(){return[]});return cache.daily}
  function loadHalf(start,end,period){var ys=years(start,end);return Promise.all(ys.map(loadAnnual)).then(function(parts){var rows=[];parts.forEach(function(p){rows=rows.concat(p)});return fetch(window.V6LiveConfig.priceHistory+'?t='+Date.now(),{cache:'no-store'}).then(function(r){return r.ok?r.json():{rows:[]}}).then(function(j){(j.rows||[]).forEach(function(r){if(r.priceTimeUTC&&r.priceGBPperMWh!==undefined)rows.push({time:r.priceTimeUTC,price:Number(r.priceGBPperMWh)})});return rows.filter(function(r){var t=new Date(r.time);if(t<start||t>end)return false;var h=t.getUTCHours();if(period==='12hday')return h>=6&&h<18;if(period==='12hnight')return h>=18||h<6;return true}).sort(function(a,b){return new Date(a.time)-new Date(b.time)})})})}
  function loadWindow(start,period){var end=new Date(start.getTime()+periodDays(period)*86400000-1000);if(isDaily(period))return loadDaily().then(function(rows){return{mode:'daily',start:start,end:end,rows:rows.filter(function(r){var t=new Date(r.date+'T12:00:00Z');return t>=start&&t<=end})}});return loadHalf(start,end,period).then(function(rows){return{mode:'half',start:start,end:end,rows:rows}})}
  return{loadWindow:loadWindow,periodDays:periodDays,isDaily:isDaily};
})();
