window.V6LoadPriceHistoryData=(function(){
  var cache={annual:{},daily:null,capture:null};
  var FIRST_YEAR=2016;
  function todayMax(){var d=new Date();return new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),23,59,59))}
  function forecastMaxDate(){return new Date(todayMax().getTime()+7*86400000)}
  function minDate(){return new Date(Date.UTC(FIRST_YEAR,0,1,0,0,0))}
  function futureMaxDate(){return forecastMaxDate()}
  function ymd(d){return d.toISOString().slice(0,10)}
  function median(vals){var a=vals.filter(function(v){return !isNaN(Number(v))}).map(Number).sort(function(x,y){return x-y});if(!a.length)return 0;var m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
  function mean(vals){var a=vals.filter(function(v){return !isNaN(Number(v))}).map(Number);return a.length?a.reduce(function(x,y){return x+y},0)/a.length:0}
  function parseCsvLine(line){var out=[],v='',q=false;for(var i=0;i<line.length;i++){var c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){v+='"';i++}else q=!q}else if(c===','&&!q){out.push(v);v=''}else v+=c}out.push(v);return out}
  function parseCsv(text){text=(text||'').trim();if(!text)return[];var lines=text.split(/\r?\n/),head=parseCsvLine(lines[0]).map(function(x){return x.trim()});return lines.slice(1).map(function(line){var cells=parseCsvLine(line),r={};head.forEach(function(h,i){r[h]=(cells[i]||'').trim()});var price=r.systemBuyPriceGBPperMWh||r.systemSellPriceGBPperMWh||r.priceGBPperMWh||'';return{source:r.source||'Elexon BMRS System Prices',priceTimeUTC:r.periodStartUTC||r.priceTimeUTC||'',capturedAtUTC:r.fetchedAtUTC||r.capturedAtUTC||'',settlementDate:r.settlementDate||'',settlementPeriod:r.settlementPeriod||'',priceGBPperMWh:price,carbonGperKWh:r.carbonGperKWh||'',priceHealth:r.priceHealth||'historical system price'}}).filter(function(r){return r.priceTimeUTC&&r.priceGBPperMWh!==''&&!isNaN(Number(r.priceGBPperMWh))})}
  function norm(rows){var seen={};return(rows||[]).filter(function(r){return r.priceTimeUTC&&r.priceGBPperMWh!==''&&!isNaN(Number(r.priceGBPperMWh))}).map(function(r){var o=Object.assign({},r);o.priceGBPperMWh=Number(o.priceGBPperMWh);return o}).sort(function(a,b){return new Date(a.priceTimeUTC)-new Date(b.priceTimeUTC)}).filter(function(r){var k=r.priceTimeUTC+'|'+r.priceGBPperMWh+'|'+(r.source||'');if(seen[k])return false;seen[k]=1;return true})}
  function periodDays(p){return {'12hday':0.5,'12hnight':0.5,'1d':1,'7d':7,'30d':30,'3m':92,'6m':183,'12m':366,'5y':1827,'10y':3653}[p]||7}
  function periodLabel(p){return {'12hday':'12 hours day','12hnight':'12 hours night','1d':'1 day','7d':'1 week','30d':'1 month','3m':'3 months','6m':'6 months','12m':'12 months','5y':'5 years','10y':'10 years'}[p]||'1 week'}
  function isDaily(p){return ['12m','5y','10y'].indexOf(p)>=0}
  function isDayNight(p){return p==='12hday'||p==='12hnight'}
  function loadAnnual(year){if(cache.annual[year])return cache.annual[year];cache.annual[year]=fetch(window.V6LiveConfig.annualBase+year+'.csv?t='+Date.now(),{cache:'no-store'}).then(function(r){return r.ok?r.text():''}).then(parseCsv).catch(function(){return[]});return cache.annual[year]}
  function loadCapture(){if(cache.capture)return cache.capture;cache.capture=fetch(window.V6LiveConfig.priceHistory+'?t='+Date.now(),{cache:'no-store'}).then(function(r){return r.ok?r.json():{rows:[]}}).then(function(j){return(j.rows||[]).map(function(r){return{source:r.source||'V6 captured Elexon Market Index Price',priceTimeUTC:r.priceTimeUTC||r.periodStartUTC||'',capturedAtUTC:r.capturedAtUTC||r.fetchedAtUTC||'',settlementDate:r.settlementDate||'',settlementPeriod:r.settlementPeriod||'',priceGBPperMWh:r.priceGBPperMWh,carbonGperKWh:r.carbonGperKWh||'',priceHealth:r.priceHealth||'captured system price'}})}).catch(function(){return[]});return cache.capture}
  function loadDaily(){if(cache.daily)return cache.daily;cache.daily=fetch(window.V6LiveConfig.dailyPriceHistory+'?t='+Date.now(),{cache:'no-store'}).then(function(r){return r.ok?r.json():{rows:[]}}).then(function(d){return d.rows||[]}).catch(function(){return[]});return cache.daily}
  function years(start,end){var out=[],last=todayMax().getUTCFullYear();for(var y=start.getUTCFullYear();y<=end.getUTCFullYear()&&y<=last;y++)out.push(y);return out}
  function selectedWindow(start,period){var min=minDate(),fmax=forecastMaxDate();if(isDayNight(period))start.setUTCHours(period==='12hday'?6:18,0,0,0);if(start<min)start=new Date(min);if(start>fmax)start=new Date(fmax);var end=new Date(start.getTime()+periodDays(period)*86400000-1000);if(end>fmax)end=new Date(fmax);return{start:start,end:end,period:period,mode:isDaily(period)?'daily':'halfhourly'}}
  function forecastWindow(meta){var tmax=todayMax(),fmax=forecastMaxDate();var start=new Date(Math.max(meta.start.getTime(),tmax.getTime()+1000));var end=new Date(Math.min(meta.end.getTime(),fmax.getTime()));if(end<=start)return null;return{start:start,end:end}}
  function buildForecastRows(all,start,end){var valid=(all||[]).filter(function(r){return r.date&&r.average!=null&&!isNaN(Number(r.average))}).sort(function(a,b){return new Date(a.date)-new Date(b.date)});if(!valid.length)return[];var recent=valid.slice(-365).map(function(r){return Number(r.average)});var level=median(recent.length?recent:valid.map(function(r){return Number(r.average)}));var monthBuckets={},dowBuckets={};valid.forEach(function(r){var d=new Date(r.date+'T12:00:00Z'),v=Number(r.average);var m=d.getUTCMonth(),dow=d.getUTCDay();(monthBuckets[m]||(monthBuckets[m]=[])).push(v-level);(dowBuckets[dow]||(dowBuckets[dow]=[])).push(v-level)});var monthOffsets={},dowOffsets={},mVals=[],dVals=[];for(var mi=0;mi<12;mi++){monthOffsets[mi]=mean(monthBuckets[mi]||[]);mVals.push(monthOffsets[mi])}for(var di=0;di<7;di++){dowOffsets[di]=mean(dowBuckets[di]||[]);dVals.push(dowOffsets[di])}var mMean=mean(mVals),dMean=mean(dVals);for(var mj=0;mj<12;mj++)monthOffsets[mj]-=mMean;for(var dj=0;dj<7;dj++)dowOffsets[dj]-=dMean;var rows=[],d=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth(),start.getUTCDate(),12,0,0));var last=new Date(Date.UTC(end.getUTCFullYear(),end.getUTCMonth(),end.getUTCDate(),12,0,0));for(;d<=last;d.setUTCDate(d.getUTCDate()+1)){var f=level+(monthOffsets[d.getUTCMonth()]||0)+(dowOffsets[d.getUTCDay()]||0);rows.push({date:ymd(d),forecast:Number(f.toFixed(2)),average:Number(f.toFixed(2)),forecastOnly:true,source:'Indicative one week seasonal baseline'})}return rows}
  function loadHalf(meta,timeMode){return Promise.all([loadCapture()].concat(years(meta.start,meta.end).map(loadAnnual))).then(function(parts){var cap=parts[0],sys=[];parts.slice(1).forEach(function(p){sys=sys.concat(p)});var all=norm(sys.concat(cap));return all.filter(function(r){var t=new Date(r.priceTimeUTC);if(t<meta.start||t>meta.end)return false;if(timeMode==='day'){var h=t.getUTCHours();return h>=6&&h<18}if(timeMode==='night'){var hn=t.getUTCHours();return hn>=18||hn<6}return true})})}
  function disclaimer(){return'Indicative one week seasonal baseline only. The dashed line is calculated from historic Elexon price behaviour and is shown only for the next 7 days.'}
  function loadWindow(start,period,timeMode){var meta=selectedWindow(new Date(start),period);var fw=forecastWindow(meta);if(meta.mode==='daily')return loadDaily().then(function(all){var rows=all.filter(function(r){var t=new Date(r.date+'T12:00:00Z');return t>=meta.start&&t<=meta.end});return{mode:'daily',start:meta.start,end:meta.end,period:period,timeMode:timeMode||'all',rows:rows,forecastRows:fw?buildForecastRows(all,fw.start,fw.end):[],forecastDisclaimer:disclaimer()}});return Promise.all([loadHalf(meta,timeMode||'all'),loadDaily()]).then(function(parts){return{mode:'halfhourly',start:meta.start,end:meta.end,period:period,timeMode:timeMode||'all',rows:parts[0],forecastRows:fw?buildForecastRows(parts[1],fw.start,fw.end):[],forecastDisclaimer:disclaimer()}})}
  return{loadWindow:loadWindow,periodDays:periodDays,periodLabel:periodLabel,isDaily:isDaily,minDate:minDate,maxDate:todayMax,futureMaxDate:futureMaxDate};
})();