window.V6LoadGenerationHistoryData=(function(){
var cache={annual:{},daily:null};
function cfg(){return window.V6GenerationHistoryConfig}
function todayMax(){var d=new Date();return new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate(),23,59,59))}
function minDate(){return new Date(Date.UTC((cfg().firstYear||2016),0,1,0,0,0))}
function parseCsvLine(line){var out=[],v='',q=false;for(var i=0;i<line.length;i++){var c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){v+='"';i++}else q=!q}else if(c===','&&!q){out.push(v);v=''}else v+=c}out.push(v);return out}
function parseCsv(text){text=(text||'').trim();if(!text)return[];var lines=text.split(/\r?\n/),head=parseCsvLine(lines[0]).map(function(x){return x.trim()});return lines.slice(1).map(function(line){var cells=parseCsvLine(line),r={};head.forEach(function(h,i){r[h]=(cells[i]||'').trim()});return r}).filter(function(r){return r.periodStartUTC&&r.fuelType&&r.generationMW!==''&&!isNaN(Number(r.generationMW))})}
function groupFor(fuel){var f=String(fuel||'').toUpperCase();if(f.indexOf('SOLAR')===0||f.indexOf('PV')===0)return'Solar';if(f.indexOf('WIND')===0)return'Wind';if(f.indexOf('NPSHYD')===0||f.indexOf('HYDRO')===0)return'Hydro';if(f.indexOf('CCGT')===0||f.indexOf('OCGT')===0)return'Gas';if(f.indexOf('COAL')===0)return'Coal';if(f.indexOf('BIOMASS')===0)return'Biomass';if(f.indexOf('NUCLEAR')===0)return'Nuclear';if(f.indexOf('PS')===0)return'Pumped Storage';if(f.indexOf('INT')===0)return'Imports & Exports';return'Other'}
function periodDays(p){return{'12hday':0.5,'12hnight':0.5,'1d':1,'24h':1,'48h':2,'7d':7,'30d':30,'3m':92,'6m':183,'12m':366,'5y':1827,'10y':3653}[p]||7}
function periodLabel(p){return{'12hday':'12 hours day','12hnight':'12 hours night','1d':'1 day','24h':'24 hours','48h':'48 hours','7d':'1 week','30d':'1 month','3m':'3 months','6m':'6 months','12m':'12 months','5y':'5 years','10y':'10 years'}[p]||'1 week'}
function isDaily(p){return['12m','5y','10y'].indexOf(p)>=0}
function isDayNight(p){return p==='12hday'||p==='12hnight'}
function isAll(t){return!t||t==='All'}
function loadAnnual(year){if(cache.annual[year])return cache.annual[year];cache.annual[year]=fetch(cfg().annualBase+year+'.csv?t='+Date.now(),{cache:'no-store'}).then(function(r){return r.ok?r.text():''}).then(parseCsv).catch(function(){return[]});return cache.annual[year]}
function loadDaily(){if(cache.daily)return cache.daily;cache.daily=fetch(cfg().dailyHistory+'?t='+Date.now(),{cache:'no-store'}).then(function(r){return r.ok?r.json():{rows:[]}}).then(function(d){return d.rows||[]}).catch(function(){return[]});return cache.daily}
function years(start,end){var out=[],last=todayMax().getUTCFullYear();for(var y=start.getUTCFullYear();y<=end.getUTCFullYear()&&y<=last;y++)out.push(y);return out}
function selectedWindow(start,period){var min=minDate(),max=todayMax();if(isDayNight(period))start.setUTCHours(period==='12hday'?6:18,0,0,0);if(start<min)start=new Date(min);if(start>max)start=new Date(max);var end=new Date(start.getTime()+periodDays(period)*86400000-1000);if(end>max)end=new Date(max);return{start:start,end:end,period:period,mode:isDaily(period)?'daily':'halfhourly'}}
function sortHalf(rows){return rows.slice().sort(function(a,b){return new Date(a.time)-new Date(b.time)})}
function sortDaily(rows){return rows.slice().sort(function(a,b){return a.date<b.date?-1:a.date>b.date?1:0})}
function dedupe(rows,fn){var seen={};return rows.filter(function(r){var k=fn(r);if(seen[k])return false;seen[k]=1;return true})}
function totalHalf(rows){var by={};rows.forEach(function(r){var k=r.time;if(!by[k])by[k]={time:k,generationMW:0,source:'Sum of generation technologies'};by[k].generationMW+=Number(r.generationMW)||0});return sortHalf(Object.keys(by).map(function(k){return by[k]}))}
function totalDaily(rows){var by={};rows.forEach(function(r){var k=r.date;if(!by[k])by[k]={date:k,averageMW:0,highMW:0,lowMW:0,source:'Sum of generation technologies'};by[k].averageMW+=Number(r.averageMW)||0;by[k].highMW+=Number(r.highMW)||0;by[k].lowMW+=Number(r.lowMW)||0});return sortDaily(Object.keys(by).map(function(k){return by[k]}))}
function seriesHalf(rows){var by={};rows.forEach(function(r){(by[r.technology]=by[r.technology]||[]).push(r)});return Object.keys(by).map(function(t){return{technology:t,rows:sortHalf(by[t])}})}
function seriesDaily(rows){var by={};rows.forEach(function(r){(by[r.technology]=by[r.technology]||[]).push(r)});return Object.keys(by).map(function(t){return{technology:t,rows:sortDaily(by[t])}})}
function loadHalf(meta,technology,timeMode){return Promise.all(years(meta.start,meta.end).map(loadAnnual)).then(function(parts){var all=[];parts.forEach(function(p){all=all.concat(p)});var rows=all.map(function(r){return{time:r.periodStartUTC,technology:groupFor(r.fuelType),generationMW:Number(r.generationMW),fuelType:r.fuelType,source:r.source||'Elexon BMRS FUELINST'}}).filter(function(r){var t=new Date(r.time);if(t<meta.start||t>meta.end)return false;if(timeMode==='day'){var h=t.getUTCHours();return h>=6&&h<18}if(timeMode==='night'){var hn=t.getUTCHours();return hn>=18||hn<6}return true});rows=dedupe(sortHalf(rows),function(r){return r.time+'|'+r.technology});if(isAll(technology))return{rows:totalHalf(rows),series:seriesHalf(rows),technology:'All generation total'};var only=sortHalf(rows.filter(function(r){return r.technology===technology}));return{rows:only,series:[{technology:technology,rows:only}],technology:technology}})}
function loadDailyWindow(meta,technology){return loadDaily().then(function(all){var rows=all.filter(function(r){var t=new Date(r.date+'T12:00:00Z');return t>=meta.start&&t<=meta.end});rows=dedupe(sortDaily(rows),function(r){return r.date+'|'+r.technology});if(isAll(technology))return{rows:totalDaily(rows),series:seriesDaily(rows),technology:'All generation total'};var only=sortDaily(rows.filter(function(r){return r.technology===technology}));return{rows:only,series:[{technology:technology,rows:only}],technology:technology}})}
function loadWindow(start,period,technology,timeMode){var meta=selectedWindow(new Date(start),period),tech=technology||'All',build=meta.mode==='daily'?loadDailyWindow(meta,tech):loadHalf(meta,tech,timeMode||'all');return build.then(function(out){return{mode:meta.mode,start:meta.start,end:meta.end,period:period,technology:out.technology,timeMode:timeMode||'all',rows:out.rows,series:out.series}})}
return{loadWindow:loadWindow,periodDays:periodDays,periodLabel:periodLabel,isDaily:isDaily,minDate:minDate,maxDate:todayMax,groupFor:groupFor};
})();
