window.V6RenderGenerationHistoryChart=(function(){
  function fmt(n,d){return n==null||isNaN(Number(n))?'—':Number(n).toLocaleString('en-GB',{minimumFractionDigits:d,maximumFractionDigits:d})}
  function niceDate(v){var d=v instanceof Date?v:new Date(String(v).replace(' ','T'));return isNaN(d.getTime())?'—':d.toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}
  function niceClock(v){var s=String(v||'');var m=s.match(/(\d{2}:\d{2})/);return m?m[1]:''}
  function valueOf(r,mode){return mode==='daily'?Number(r.averageMW):Number(r.generationMW)}
  function timeOf(r,mode){return mode==='daily'?r.date+'T12:00:00Z':r.time}
  function colour(tech){return {'Solar':'#f5c518','Wind':'#00d0ff','Hydro':'#0090c0','Gas':'#c0399a','Coal':'#888888','Biomass':'#f59e2b','Nuclear':'#5cb85c','Pumped Storage':'#9b59b6','Imports & Exports':'#e8615a','Other':'#a6adbb'}[tech]||'#00ffff'}
  function dateLabel(t,span){return span>45*86400000?new Date(t).toLocaleDateString('en-GB',{month:'long',year:'numeric'}):new Date(t).toLocaleDateString('en-GB')}
  function shortTickLabel(t,span){var d=new Date(t);if(span<=2.1*86400000)return d.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false});return d.toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'})}
  function stats(result){var rows=result.rows||[];if(!rows.length)return null;var h=rows[0],l=rows[0],s=0;rows.forEach(function(r){var v=valueOf(r,result.mode);s+=v;if(v>valueOf(h,result.mode))h=r;if(v<valueOf(l,result.mode))l=r});return{hi:h,lo:l,avg:s/rows.length,hiValue:valueOf(h,result.mode),loValue:valueOf(l,result.mode),hiDate:niceDate(timeOf(h,result.mode)),loDate:niceDate(timeOf(l,result.mode)),hiClock:niceClock(timeOf(h,result.mode)),loClock:niceClock(timeOf(l,result.mode)),avgDate:niceDate(result.start)+' to '+niceDate(result.end)}}
  function minMax(rows,mode){var lo=0,hi=0;rows.forEach(function(r){var v=valueOf(r,mode);if(v<lo)lo=v;if(v>hi)hi=v});if(lo===hi)hi=lo+1;var m=Math.max((hi-lo)*.08,50);return{lo:lo-m,hi:hi+m}}
  function step(span){var raw=span/8,p=Math.pow(10,Math.floor(Math.log10(Math.max(raw,1)))),n=raw/p;if(n<=1)return p;if(n<=2)return 2*p;if(n<=5)return 5*p;return 10*p}
  function drawAxes(g,w,h,q,mm,pad,t0,t1){var st=step(mm.hi-mm.lo),start=Math.ceil(mm.lo/st)*st,span=t1-t0;g.font=11*q+'px Courier New';for(var v=start;v<=mm.hi+st*.5;v+=st){var y=pad.top+((mm.hi-v)/(mm.hi-mm.lo))*(h-pad.top-pad.bottom);g.fillStyle='#f5f7fb';g.textAlign='left';g.fillText(fmt(v,0)+' MW',8*q,y+4*q);g.strokeStyle='rgba(255,255,255,.06)';g.beginPath();g.moveTo(pad.left,y);g.lineTo(w-pad.right,y);g.stroke()}g.strokeStyle='rgba(255,255,255,.26)';g.beginPath();g.moveTo(pad.left,h-pad.bottom);g.lineTo(w-pad.right,h-pad.bottom);g.stroke();g.fillStyle='#f5f7fb';g.textAlign='left';g.fillText(dateLabel(t0,span),pad.left,h-pad.bottom+24*q);g.textAlign='right';g.fillText(dateLabel(t1,span),w-pad.right,h-pad.bottom+24*q);if(span<=7.1*86400000){var interval=span<=1.1*86400000?3*3600000:span<=2.1*86400000?6*3600000:86400000;var first=Math.ceil(t0/interval)*interval;g.textAlign='center';for(var t=first;t<t1;t+=interval){var x=pad.left+((t-t0)/(t1-t0))*(w-pad.left-pad.right);g.strokeStyle='rgba(255,255,255,.10)';g.beginPath();g.moveTo(x,pad.top);g.lineTo(x,h-pad.bottom);g.stroke();g.fillStyle='#9aa3b6';g.fillText(shortTickLabel(t,span),x,h-pad.bottom+42*q)}}}
  function drawLine(g,rows,result,w,h,q,pad,mm,t0,t1){if(!rows.length)return;var plotW=w-pad.left-pad.right,plotH=h-pad.top-pad.bottom;function X(r){var t=new Date(timeOf(r,result.mode)).getTime();return pad.left+((t-t0)/(t1-t0))*plotW}function Y(v){return pad.top+((mm.hi-v)/(mm.hi-mm.lo))*plotH}g.save();g.strokeStyle=colour(result.technology);g.lineWidth=2*q;g.shadowColor=colour(result.technology);g.shadowBlur=6*q;g.beginPath();rows.forEach(function(r,i){var x=X(r),y=Y(valueOf(r,result.mode));if(i===0)g.moveTo(x,y);else g.lineTo(x,y)});g.stroke();g.shadowBlur=0;var s=stats(result);if(s){[['HIGH',s.hi,s.hiValue],['LOW',s.lo,s.loValue]].forEach(function(item){var x=X(item[1]),y=Y(item[2]);g.fillStyle='#ff3333';g.beginPath();g.arc(x,y,5*q,0,Math.PI*2);g.fill()})}g.restore()}
  function render(canvas,result){var rows=result.rows||[],ctx=canvas.getContext('2d'),box=canvas.getBoundingClientRect(),q=window.devicePixelRatio||1,w=Math.max(600,Math.floor(box.width*q)),h=Math.max(360,Math.floor((box.height||520)*q));canvas.width=w;canvas.height=h;ctx.clearRect(0,0,w,h);ctx.fillStyle='#05070c';ctx.fillRect(0,0,w,h);ctx.font=14*q+'px Courier New';ctx.fillStyle='#00ffff';ctx.textAlign='left';ctx.fillText('GB GENERATION HISTORY · '+(result.technology||'Technology')+' · '+result.mode.toUpperCase(),18*q,28*q);if(!rows.length){ctx.fillStyle='#9aa3b6';ctx.fillText('Awaiting generation history data.',18*q,70*q);return}var pad={left:88*q,right:28*q,top:56*q,bottom:84*q},t0=result.start.getTime(),t1=result.end.getTime(),mm=minMax(rows,result.mode);drawAxes(ctx,w,h,q,mm,pad,t0,t1);drawLine(ctx,rows,result,w,h,q,pad,mm,t0,t1);var s=stats(result);if(s){ctx.fillStyle='rgba(5,7,12,.90)';ctx.strokeStyle='rgba(0,255,255,.35)';ctx.beginPath();ctx.roundRect(18*q,h-62*q,w-36*q,44*q,8*q);ctx.fill();ctx.stroke();ctx.fillStyle='#f5f7fb';ctx.font=11*q+'px Courier New';ctx.textAlign='left';ctx.fillText('High '+fmt(s.hiValue,1)+' MW on '+s.hiDate+' '+s.hiClock,30*q,h-38*q);ctx.textAlign='right';ctx.fillText('Low '+fmt(s.loValue,1)+' MW on '+s.loDate+' '+s.loClock,w-30*q,h-38*q)}}
  return{render:render};
})();
