window.V6RenderSolarDailyMwhChart=(function(){
  function fmt(n,d){return n==null||isNaN(Number(n))?'—':Number(n).toLocaleString('en-GB',{minimumFractionDigits:d,maximumFractionDigits:d})}
  function niceDate(v){var d=v instanceof Date?v:new Date(String(v).replace(' ','T'));return isNaN(d.getTime())?'—':d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}
  function dateLabel(t,span){var d=new Date(t);return span>45*86400000?d.toLocaleDateString('en-GB',{month:'short',year:'numeric'}):d.toLocaleDateString('en-GB',{day:'2-digit',month:'short'})}
  function val(r){return Number(r.mwh)}
  function tm(r){return r.date+'T12:00:00Z'}
  function colour(tech){return {'Solar':'#f5c518','Wind':'#00d0ff','Hydro':'#0090c0','Gas':'#ff4fbf','Coal':'#888888','Biomass':'#f59e2b','Nuclear':'#5cff8d','Pumped Storage':'#b16cff','Imports & Exports':'#e8615a','Other':'#a6adbb','All generation total':'#00ffff'}[tech]||'#00ffff'}
  function stats(rows){var best=null,total=0,n=0;rows.forEach(function(r){var v=val(r);if(isNaN(v))return;total+=v;n++;if(!best||v>val(best))best=r});return best?{best:best,bestValue:val(best),bestDate:niceDate(tm(best)),mean:total/n,total:total,range:niceDate(tm(rows[0]))+' to '+niceDate(tm(rows[rows.length-1]))}:null}
  function mm(rows){var lo=0,hi=1;rows.forEach(function(r){var v=val(r);if(isNaN(v))return;if(v>hi)hi=v;if(v<lo)lo=v});return{lo:lo<0?lo*1.08:0,hi:hi*1.08}}
  function step(span){var raw=span/5,p=Math.pow(10,Math.floor(Math.log10(Math.max(raw,1)))),n=raw/p;if(n<=1)return p;if(n<=2)return 2*p;if(n<=5)return 5*p;return 10*p}
  function points(w,h,pad,scale,t0,t1){var pw=w-pad.left-pad.right,ph=h-pad.top-pad.bottom;return{X:function(r){var t=new Date(tm(r)).getTime();return pad.left+((t-t0)/(t1-t0))*pw},Y:function(v){return pad.top+((scale.hi-v)/(scale.hi-scale.lo))*ph}}}
  function drawTicks(g,w,h,q,scale,pad,t0,t1){var st=step(scale.hi-scale.lo),start=Math.ceil(scale.lo/st)*st,span=t1-t0;g.save();g.font=(w/q<520?9:11)*q+'px Courier New';for(var v=start;v<=scale.hi+st*.5;v+=st){var y=pad.top+((scale.hi-v)/(scale.hi-scale.lo))*(h-pad.top-pad.bottom);g.fillStyle='#d8deeb';g.textAlign='left';g.fillText(fmt(v,0)+' MWh',8*q,y+4*q);g.strokeStyle='rgba(255,255,255,.055)';g.beginPath();g.moveTo(pad.left,y);g.lineTo(w-pad.right,y);g.stroke()}g.strokeStyle='rgba(255,255,255,.26)';g.beginPath();g.moveTo(pad.left,h-pad.bottom);g.lineTo(w-pad.right,h-pad.bottom);g.stroke();g.fillStyle='#d8deeb';g.textAlign='left';g.fillText(dateLabel(t0,span),pad.left,h-pad.bottom+24*q);g.textAlign='right';g.fillText(dateLabel(t1,span),w-pad.right,h-pad.bottom+24*q);g.restore()}
  function callout(g,s,p,q,w,h,pad){var x=p.X(s.best),y=p.Y(s.bestValue),tx=Math.max(pad.left+180*q,Math.min(w-pad.right-180*q,x+22*q)),ty=Math.max(pad.top+48*q,y-30*q);g.save();g.strokeStyle='#ff3333';g.shadowColor='rgba(0,255,255,.55)';g.shadowBlur=7*q;g.beginPath();g.moveTo(x,y);g.lineTo(tx,ty);g.stroke();var lines=['HIGHEST DAILY ENERGY',fmt(s.bestValue,1)+' MWh',s.bestDate],lh=17*q,bw=0;g.font='900 '+(w/q<520?10:13)*q+'px Courier New';lines.forEach(function(t){bw=Math.max(bw,g.measureText(t).width)});g.fillStyle='rgba(5,7,12,.84)';g.strokeStyle='rgba(0,255,255,.45)';g.beginPath();g.roundRect(tx,ty-58*q,bw+18*q,58*q,7*q);g.fill();g.stroke();g.fillStyle='#ff3333';lines.forEach(function(t,i){g.fillText(t,tx+9*q,ty-38*q+i*17*q)});g.restore()}
  function drawSummary(g,s,q,w,h,pad){var y=h-72*q,bw=w-pad.left-pad.right,x=pad.left,col=bw/3;g.save();g.fillStyle='rgba(5,7,12,.92)';g.strokeStyle='rgba(0,255,255,.42)';g.beginPath();g.roundRect(x,y,bw,52*q,9*q);g.fill();g.stroke();function cell(i,l,v,sub,c){var cx=x+i*col+12*q;g.fillStyle='#9aa3b6';g.font='900 '+9*q+'px Courier New';g.fillText(l,cx,y+16*q);g.fillStyle=c;g.font='900 '+(w/q<520?10:12)*q+'px Courier New';g.fillText(v,cx,y+32*q);g.fillStyle='#d8deeb';g.font=(w/q<520?7.5:8.5)*q+'px Courier New';g.fillText(sub,cx,y+45*q)}cell(0,'HIGHEST DAY',fmt(s.bestValue,1)+' MWh',s.bestDate,'#ff4444');cell(1,'MEAN DAILY',fmt(s.mean,1)+' MWh',s.range,'#00ffff');cell(2,'TOTAL SHOWN',fmt(s.total/1000000,2)+' TWh','Selected range','#f5c518');g.restore()}
  function render(canvas,result){var tech=result.technology||'Technology',rows=(result.rows||[]).filter(function(r){return r&&r.mwh!=null&&!isNaN(Number(r.mwh))});var ctx=canvas.getContext('2d'),box=canvas.getBoundingClientRect(),q=window.devicePixelRatio||1,cssW=Math.max(320,Math.floor(box.width||canvas.clientWidth||600)),cssH=Math.max(360,Math.floor(box.height||canvas.clientHeight||440)),w=Math.floor(cssW*q),h=Math.floor(cssH*q);canvas.width=w;canvas.height=h;ctx.fillStyle='#05070c';ctx.fillRect(0,0,w,h);ctx.font='900 '+(cssW<520?11:15)*q+'px Courier New';ctx.fillStyle='#00ffff';ctx.fillText('DAILY ENERGY OUTPUT · '+tech+' · MWh',18*q,28*q);if(!rows.length){ctx.fillStyle='#9aa3b6';ctx.font=13*q+'px Courier New';ctx.fillText('Awaiting daily MWh data.',18*q,90*q);return}var pad={left:(cssW<520?86:96)*q,right:(cssW<520?20:30)*q,top:76*q,bottom:116*q},t0=result.start.getTime(),t1=result.end.getTime(),scale=mm(rows),p=points(w,h,pad,scale,t0,t1),c=colour(tech);drawTicks(ctx,w,h,q,scale,pad,t0,t1);ctx.save();ctx.strokeStyle=c;ctx.lineWidth=2.1*q;ctx.shadowColor=c;ctx.shadowBlur=9*q;ctx.beginPath();rows.forEach(function(r,i){var x=p.X(r),y=p.Y(val(r));if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.stroke();ctx.restore();var s=stats(rows);if(s){ctx.fillStyle='#ff3333';ctx.beginPath();ctx.arc(p.X(s.best),p.Y(s.bestValue),5*q,0,Math.PI*2);ctx.fill();callout(ctx,s,p,q,w,h,pad);drawSummary(ctx,s,q,w,h,pad)}}
  return{render:render};
})();
