window.V6RenderGenerationHistoryChart=(function(){
  function fmt(n,d){return n==null||isNaN(Number(n))?'—':Number(n).toLocaleString('en-GB',{minimumFractionDigits:d,maximumFractionDigits:d})}
  function niceDate(v){var d=v instanceof Date?v:new Date(String(v).replace(' ','T'));return isNaN(d.getTime())?'—':d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}
  function niceClock(v){var s=String(v||'');var m=s.match(/(\d{2}:\d{2})/);return m?m[1]:''}
  function valueOf(r,mode){return mode==='daily'?Number(r.averageMW):Number(r.generationMW)}
  function timeOf(r,mode){return mode==='daily'?r.date+'T12:00:00Z':r.time}
  function colour(tech){return {'Solar':'#f5c518','Wind':'#00d0ff','Hydro':'#0090c0','Gas':'#ff4fbf','Coal':'#888888','Biomass':'#f59e2b','Nuclear':'#5cff8d','Pumped Storage':'#b16cff','Imports & Exports':'#e8615a','Other':'#a6adbb','All generation total':'#00ffff'}[tech]||'#00ffff'}
  function compactMode(mode){return mode==='daily'?'Daily average':'30 min output'}
  function dateLabel(t,span){var d=new Date(t);return span>45*86400000?d.toLocaleDateString('en-GB',{month:'short',year:'numeric'}):d.toLocaleDateString('en-GB',{day:'2-digit',month:'short'})}
  function shortTickLabel(t,span){var d=new Date(t);if(span<=2.1*86400000)return d.toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false});return d.toLocaleDateString('en-GB',{weekday:'short',day:'numeric',month:'short'})}
  function stats(result){var rows=result.rows||[];if(!rows.length)return null;var h=rows[0],l=rows[0],s=0,n=0;rows.forEach(function(r){var v=valueOf(r,result.mode);if(isNaN(v))return;s+=v;n++;if(v>valueOf(h,result.mode))h=r;if(v<valueOf(l,result.mode))l=r});return n?{hi:h,lo:l,avg:s/n,hiValue:valueOf(h,result.mode),loValue:valueOf(l,result.mode),hiDate:niceDate(timeOf(h,result.mode)),loDate:niceDate(timeOf(l,result.mode)),hiClock:niceClock(timeOf(h,result.mode)),loClock:niceClock(timeOf(l,result.mode)),avgDate:niceDate(result.start)+' to '+niceDate(result.end)}:null}
  function minMax(rows,mode){var lo=0,hi=0;rows.forEach(function(r){var v=valueOf(r,mode);if(isNaN(v))return;if(v<lo)lo=v;if(v>hi)hi=v});if(lo===hi)hi=lo+1;var m=Math.max((hi-lo)*.10,50);return{lo:lo-m,hi:hi+m}}
  function step(span){var raw=span/5,p=Math.pow(10,Math.floor(Math.log10(Math.max(raw,1)))),n=raw/p;if(n<=1)return p;if(n<=2)return 2*p;if(n<=5)return 5*p;return 10*p}
  function drawTitle(g,result,q,w,pad,cssW){var c=colour(result.technology);g.save();g.font='900 '+(cssW<520?11:15)*q+'px Courier New';g.fillStyle='#00ffff';g.textAlign='left';var title=(cssW<520?'GB GEN · ':'GB GENERATION HISTORY · ')+(result.technology||'Technology')+' · '+compactMode(result.mode);g.fillText(title,18*q,28*q);var lx=pad.left,ly=pad.top-24*q;g.shadowColor=c;g.shadowBlur=6*q;g.fillStyle=c;g.fillRect(lx,ly-8*q,9*q,9*q);g.shadowBlur=0;g.fillStyle='#9aa3b6';g.font=(cssW<520?9:10)*q+'px Courier New';g.fillText(result.technology||'Technology',lx+14*q,ly);g.fillText(compactMode(result.mode),lx+(cssW<520?100:130)*q,ly);g.restore()}
  function drawTicks(g,w,h,q,mm,pad,t0,t1){var st=step(mm.hi-mm.lo),start=Math.ceil(mm.lo/st)*st,span=t1-t0,plotW=w-pad.left-pad.right;g.save();g.font=(w/q<520?9:11)*q+'px Courier New';for(var v=start;v<=mm.hi+st*.5;v+=st){var y=pad.top+((mm.hi-v)/(mm.hi-mm.lo))*(h-pad.top-pad.bottom);g.fillStyle='#d8deeb';g.textAlign='left';g.fillText(fmt(v,0)+' MW',8*q,y+4*q);g.strokeStyle='rgba(255,255,255,.055)';g.beginPath();g.moveTo(pad.left,y);g.lineTo(w-pad.right,y);g.stroke()}g.strokeStyle='rgba(255,255,255,.26)';g.beginPath();g.moveTo(pad.left,h-pad.bottom);g.lineTo(w-pad.right,h-pad.bottom);g.stroke();g.fillStyle='#d8deeb';g.textAlign='left';g.fillText(dateLabel(t0,span),pad.left,h-pad.bottom+24*q);g.textAlign='right';g.fillText(dateLabel(t1,span),w-pad.right,h-pad.bottom+24*q);if(span<=35*86400000){var interval=span<=2.1*86400000?6*3600000:86400000,first=Math.ceil(t0/interval)*interval;g.textAlign='center';for(var t=first;t<t1;t+=interval){var x=pad.left+((t-t0)/(t1-t0))*plotW;g.strokeStyle='rgba(255,255,255,.10)';g.beginPath();g.moveTo(x,pad.top);g.lineTo(x,h-pad.bottom);g.stroke();g.fillStyle='rgba(154,163,182,.75)';g.fillText(shortTickLabel(t,span),x,h-pad.bottom+42*q)}}g.restore()}
  function pointFns(result,w,h,pad,mm,t0,t1){var plotW=w-pad.left-pad.right,plotH=h-pad.top-pad.bottom;return{X:function(r){var t=new Date(timeOf(r,result.mode)).getTime();return pad.left+((t-t0)/(t1-t0))*plotW},Y:function(v){return pad.top+((mm.hi-v)/(mm.hi-mm.lo))*plotH}}}
  function callout(g,label,val,date,clock,x,y,q,w,h,pad,c){var left=x<w/2,tx=left?Math.min(w-pad.right-160*q,x+18*q):Math.max(pad.left+160*q,x-18*q),ty=Math.max(pad.top+54*q,Math.min(h-pad.bottom-28*q,y+(label==='HIGH'?-24:58)*q));g.save();g.strokeStyle='#ff3333';g.lineWidth=1.4*q;g.shadowColor='rgba(0,255,255,.55)';g.shadowBlur=7*q;g.beginPath();g.moveTo(x,y);g.lineTo(tx,ty-24*q);g.stroke();var lines=[label,fmt(val,1)+' MW',date+(clock?' '+clock:'')],lh=17*q,bw=0;g.font='900 '+(w/q<520?10:13)*q+'px Courier New';lines.forEach(function(t){bw=Math.max(bw,g.measureText(t).width)});var padb=8*q,bh=lines.length*lh+padb*2,bx=left?tx:tx-bw-padb*2;g.fillStyle='rgba(5,7,12,.82)';g.strokeStyle='rgba(0,255,255,.45)';g.lineWidth=1*q;g.beginPath();g.roundRect(bx,ty-bh+4*q,bw+padb*2,bh,7*q);g.fill();g.stroke();g.fillStyle='#ff3333';g.textAlign=left?'left':'right';var textX=left?tx+padb:tx-padb;lines.forEach(function(t,i){g.fillText(t,textX,ty-(lines.length-1-i)*lh)});g.restore()}
  function drawLine(g,rows,result,w,h,q,pad,mm,t0,t1){if(!rows.length)return;var c=colour(result.technology),p=pointFns(result,w,h,pad,mm,t0,t1);g.save();g.strokeStyle=c;g.lineWidth=2.2*q;g.shadowColor=c;g.shadowBlur=9*q;g.beginPath();rows.forEach(function(r,i){var x=p.X(r),y=p.Y(valueOf(r,result.mode));if(i===0)g.moveTo(x,y);else g.lineTo(x,y)});g.stroke();g.shadowBlur=0;if(rows.length<80){g.fillStyle=c;rows.forEach(function(r){var x=p.X(r),y=p.Y(valueOf(r,result.mode));g.beginPath();g.arc(x,y,2.4*q,0,Math.PI*2);g.fill()})}var s=stats(result);if(s){[[s.hi,s.hiValue],[s.lo,s.loValue]].forEach(function(it){g.fillStyle='#ff3333';g.shadowColor='rgba(0,255,255,.85)';g.shadowBlur=8*q;g.beginPath();g.arc(p.X(it[0]),p.Y(it[1]),5*q,0,Math.PI*2);g.fill()});callout(g,'HIGH',s.hiValue,s.hiDate,s.hiClock,p.X(s.hi),p.Y(s.hiValue),q,w,h,pad,c);callout(g,'LOW',s.loValue,s.loDate,s.loClock,p.X(s.lo),p.Y(s.loValue),q,w,h,pad,c)}g.restore()}
  function drawSummary(g,s,q,w,h,pad){if(!s)return;var y=h-72*q,bw=w-pad.left-pad.right,x=pad.left,cols=3,col=bw/cols;g.save();g.fillStyle='rgba(5,7,12,.92)';g.strokeStyle='rgba(0,255,255,.42)';g.shadowColor='rgba(0,255,255,.18)';g.shadowBlur=8*q;g.beginPath();g.roundRect(x,y,bw,52*q,9*q);g.fill();g.stroke();g.shadowBlur=0;function cell(i,label,value,sub,accent){var cx=x+i*col+12*q;g.fillStyle='#9aa3b6';g.font='900 '+9*q+'px Courier New';g.textAlign='left';g.fillText(label,cx,y+16*q);g.fillStyle=accent;g.font='900 '+(w/q<520?10:12)*q+'px Courier New';g.fillText(value,cx,y+32*q);g.fillStyle='#d8deeb';g.font=(w/q<520?7.5:8.5)*q+'px Courier New';g.fillText(sub,cx,y+45*q)}cell(0,'HIGH',fmt(s.hiValue,1)+' MW',s.hiDate,'#ff4444');cell(1,'MEAN',fmt(s.avg,1)+' MW',s.avgDate,'#00ffff');cell(2,'LOW',fmt(s.loValue,1)+' MW',s.loDate,'#ff4444');g.restore()}
  function render(canvas,result){var rows=result.rows||[],ctx=canvas.getContext('2d'),box=canvas.getBoundingClientRect(),q=window.devicePixelRatio||1,cssW=Math.max(320,Math.floor(box.width||canvas.clientWidth||600)),cssH=Math.max(420,Math.floor(box.height||canvas.clientHeight||520)),w=Math.floor(cssW*q),h=Math.floor(cssH*q);canvas.width=w;canvas.height=h;ctx.clearRect(0,0,w,h);ctx.fillStyle='#05070c';ctx.fillRect(0,0,w,h);var pad={left:(cssW<520?78:88)*q,right:(cssW<520?20:30)*q,top:66*q,bottom:116*q};drawTitle(ctx,result,q,w,pad,cssW);if(!rows.length){ctx.fillStyle='#9aa3b6';ctx.font=13*q+'px Courier New';ctx.fillText('Awaiting generation history data.',18*q,76*q);return}var t0=result.start.getTime(),t1=result.end.getTime(),mm=minMax(rows,result.mode);drawTicks(ctx,w,h,q,mm,pad,t0,t1);drawLine(ctx,rows,result,w,h,q,pad,mm,t0,t1);drawSummary(ctx,stats(result),q,w,h,pad)}
  return{render:render};
})();