window.V6RenderSolarDailyMwhChart=(function(){
  var lastResult=null, inspectState={};
  function fmt(n,d){return n==null||isNaN(Number(n))?'—':Number(n).toLocaleString('en-GB',{minimumFractionDigits:d,maximumFractionDigits:d})}
  function niceDate(v){var d=v instanceof Date?v:new Date(String(v).replace(' ','T'));return isNaN(d.getTime())?'—':d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}
  function dateLabel(t,span){var d=new Date(t);return span>45*86400000?d.toLocaleDateString('en-GB',{month:'short',year:'numeric'}):d.toLocaleDateString('en-GB',{day:'2-digit',month:'short'})}
  function val(r){return Number(r.mwh)}
  function tm(r){return r.date+'T12:00:00Z'}
  function rowsOf(result){return (result.rows||[]).filter(function(r){return r&&r.mwh!=null&&!isNaN(Number(r.mwh))})}
  function stats(rows){var hi=null,lo=null,total=0,n=0;rows.forEach(function(r){var v=val(r);if(isNaN(v))return;total+=v;n++;if(!hi||v>val(hi))hi=r;if(!lo||v<val(lo))lo=r});return hi&&lo?{hi:hi,lo:lo,hiValue:val(hi),loValue:val(lo),hiDate:niceDate(tm(hi)),loDate:niceDate(tm(lo)),mean:total/n,total:total,range:niceDate(tm(rows[0]))+' to '+niceDate(tm(rows[rows.length-1]))}:null}
  function mm(rows){var hi=1;rows.forEach(function(r){var v=val(r);if(!isNaN(v)&&v>hi)hi=v});return{lo:0,hi:hi*1.10}}
  function step(span){var raw=span/5,p=Math.pow(10,Math.floor(Math.log10(Math.max(raw,1)))),n=raw/p;if(n<=1)return p;if(n<=2)return 2*p;if(n<=5)return 5*p;return 10*p}
  function points(w,h,pad,scale,t0,t1){var pw=w-pad.left-pad.right,ph=h-pad.top-pad.bottom;return{X:function(r){var t=new Date(tm(r)).getTime();return pad.left+((t-t0)/(t1-t0))*pw},Y:function(v){return pad.top+((scale.hi-v)/(scale.hi-scale.lo))*ph}}}
  function seasonName(t){var m=new Date(t).getUTCMonth()+1;if(m===12||m<=2)return'Winter';if(m>=3&&m<=5)return'Spring';if(m>=6&&m<=8)return'Summer';return'Autumn'}
  function seasonColor(t){var s=seasonName(t);if(s==='Winter')return'#00ffff';if(s==='Spring')return'#00ff88';if(s==='Summer')return'#ffcc00';return'#c79245'}
  function drawSeasonKey(g,q,pad){var items=[['Winter','#00ffff'],['Spring','#00ff88'],['Summer','#ffcc00'],['Autumn','#c79245']],x=pad.left,y=pad.top-28*q;g.save();g.font=9*q+'px Courier New';items.forEach(function(it){g.fillStyle=it[1];g.shadowColor=it[1];g.shadowBlur=4*q;g.fillRect(x,y-7*q,8*q,8*q);g.shadowBlur=0;g.fillStyle='#9aa3b6';g.fillText(it[0],x+12*q,y);x+=58*q});g.restore()}
  function drawSeasonLine(g,rows,p,q){g.save();g.lineWidth=2.15*q;g.lineCap='round';g.lineJoin='round';for(var i=1;i<rows.length;i++){var a=rows[i-1],b=rows[i],col=seasonColor(tm(b));g.strokeStyle=col;g.shadowColor=col;g.shadowBlur=8*q;g.beginPath();g.moveTo(p.X(a),p.Y(val(a)));g.lineTo(p.X(b),p.Y(val(b)));g.stroke()}g.restore()}
  function drawTicks(g,w,h,q,scale,pad,t0,t1){var st=step(scale.hi-scale.lo),span=t1-t0;g.save();g.font=(w/q<520?9:11)*q+'px Courier New';for(var v=0;v<=scale.hi+st*.5;v+=st){var y=pad.top+((scale.hi-v)/(scale.hi-scale.lo))*(h-pad.top-pad.bottom);g.fillStyle='#d8deeb';g.textAlign='left';g.fillText(fmt(v,0)+' MWh',8*q,y+4*q);g.strokeStyle='rgba(255,255,255,.055)';g.beginPath();g.moveTo(pad.left,y);g.lineTo(w-pad.right,y);g.stroke()}g.strokeStyle='rgba(255,255,255,.26)';g.beginPath();g.moveTo(pad.left,h-pad.bottom);g.lineTo(w-pad.right,h-pad.bottom);g.stroke();g.fillStyle='#d8deeb';g.textAlign='left';g.fillText(dateLabel(t0,span),pad.left,h-pad.bottom+24*q);g.textAlign='right';g.fillText(dateLabel(t1,span),w-pad.right,h-pad.bottom+24*q);g.restore()}
  function eventBox(g,lines,q,x,y,align){var pad=8*q,lh=17*q,wid=0;g.save();g.font='900 '+13*q+'px Courier New';lines.forEach(function(t){wid=Math.max(wid,g.measureText(t).width)});var bh=lines.length*lh+pad*2,xx=align==='right'?x-wid-pad*2:x;g.fillStyle='rgba(5,7,12,.84)';g.strokeStyle='rgba(0,255,255,.45)';g.beginPath();g.roundRect(xx,y-bh+4*q,wid+pad*2,bh,6*q);g.fill();g.stroke();g.fillStyle='#ff3333';g.textAlign=align;lines.forEach(function(t,i){g.fillText(t,x,y-(lines.length-1-i)*lh)});g.restore()}
  function pointer(g,point,q,x,y){g.save();g.strokeStyle='#ff3333';g.shadowColor='rgba(0,255,255,.55)';g.shadowBlur=7*q;g.setLineDash([]);g.beginPath();g.moveTo(point.x,point.y);g.lineTo(x,y-24*q);g.stroke();g.restore()}
  function callout(g,label,value,date,x,y,q,w,h,pad){var right=x>w/2,tx=right?Math.max(pad.left+160*q,x-18*q):Math.min(w-pad.right-160*q,x+18*q),ty=label==='HIGH'?Math.max(pad.top+54*q,y-24*q):Math.min(h-pad.bottom-28*q,y+54*q);pointer(g,{x:x,y:y},q,tx,ty);eventBox(g,[label,fmt(value,1)+' MWh',date],q,tx,ty,right?'right':'left')}
  function drawSummary(g,s,q,w,h,pad,isFull){if(isFull&&w/q>h/q)return;var mobile=w/q<620,x=pad.left,bw=w-pad.left-pad.right,y=h-(mobile?116:72)*q,rows=mobile?2:1,cols=mobile?2:4,cellH=mobile?46*q:52*q,col=bw/cols;g.save();g.fillStyle='rgba(5,7,12,.92)';g.strokeStyle='rgba(0,255,255,.42)';g.beginPath();g.roundRect(x,y,bw,rows*cellH,9*q);g.fill();g.stroke();function cell(i,l,v,sub,c){var r=mobile?Math.floor(i/2):0,cc=mobile?i%2:i,cx=x+cc*col+12*q,cy=y+r*cellH;g.fillStyle='#9aa3b6';g.font='900 '+(mobile?8:9)*q+'px Courier New';g.fillText(l,cx,cy+16*q);g.fillStyle=c;g.font='900 '+(mobile?9:12)*q+'px Courier New';g.fillText(v,cx,cy+32*q);g.fillStyle='#d8deeb';g.font=(mobile?7:8.5)*q+'px Courier New';g.fillText(sub,cx,cy+45*q)}cell(0,'HIGH DAY',fmt(s.hiValue,1)+' MWh',s.hiDate,'#ff4444');cell(1,'LOW DAY',fmt(s.loValue,1)+' MWh',s.loDate,'#ff4444');cell(2,'MEAN DAILY',fmt(s.mean,1)+' MWh',s.range,'#00ffff');cell(3,'TOTAL SHOWN',fmt(s.total/1000000,2)+' TWh','Selected range','#f5c518');g.restore()}
  function inspectKey(result){return [result.start&&result.start.toISOString?result.start.toISOString():String(result.start),result.end&&result.end.toISOString?result.end.toISOString():String(result.end),(result.rows||[]).length].join('|')}
  function nearest(rows,target){var best=0,bestD=Infinity;for(var i=0;i<rows.length;i++){var d=Math.abs(new Date(tm(rows[i])).getTime()-target);if(d<bestD){bestD=d;best=i}}return best}
  function ensureInspectState(canvasId,result,rows){var key=inspectKey(result),st=inspectState[canvasId]||{};if(st.key!==key){st={key:key,index:0,moved:false};if(rows.length){var s=stats(rows);st.index=rows.indexOf(s.hi)}inspectState[canvasId]=st}return st}
  function ensureInspectControls(canvasId,result){var c=document.getElementById(canvasId);if(!c||c.dataset.solarInspectControls==='1')return;c.dataset.solarInspectControls='1';var bar=document.createElement('div');bar.id=canvasId+'-inspect-controls';bar.className='solar-mwh-inspect-controls';var prev=document.createElement('button');prev.type='button';prev.textContent='◀ previous day';prev.className='solar-mwh-inspect-button';var out=document.createElement('div');out.id=canvasId+'-inspect-readout';out.className='solar-mwh-inspect-readout';out.textContent='Click or touch the chart to inspect a day.';var next=document.createElement('button');next.type='button';next.textContent='next day ▶';next.className='solar-mwh-inspect-button';function step(dir){if(!lastResult)return;var rows=rowsOf(lastResult),st=ensureInspectState(canvasId,lastResult,rows);st.index=Math.max(0,Math.min(rows.length-1,st.index+dir));st.moved=true;renderTo(canvasId,lastResult)}prev.addEventListener('click',function(){step(-1)});next.addEventListener('click',function(){step(1)});bar.appendChild(prev);bar.appendChild(out);bar.appendChild(next);if(c.parentNode)c.parentNode.insertBefore(bar,c.nextSibling)}
  function updateInspect(canvasId,result,row,idx,total){var bar=document.getElementById(canvasId+'-inspect-controls'),out=document.getElementById(canvasId+'-inspect-readout');if(!bar)return;bar.style.display='flex';if(out&&row)out.textContent=niceDate(tm(row))+' | '+fmt(val(row),1)+' MWh | point '+(idx+1)+' of '+total.toLocaleString('en-GB')}
  function attachInspectEvents(canvasId){var c=document.getElementById(canvasId);if(!c||c.dataset.solarInspectEvents==='1')return;c.dataset.solarInspectEvents='1';function move(ev){if(!lastResult)return;var st=inspectState[canvasId];if(!st||!st.geom)return;var rect=c.getBoundingClientRect(),q=window.devicePixelRatio||1,x=(ev.clientX-rect.left)*q,geo=st.geom;if(x<geo.pad.left||x>geo.w-geo.pad.right)return;var target=geo.t0+((x-geo.pad.left)/(geo.w-geo.pad.left-geo.pad.right))*(geo.t1-geo.t0),rows=rowsOf(lastResult);st.index=nearest(rows,target);st.moved=true;renderTo(canvasId,lastResult)}c.addEventListener('pointerdown',move);c.addEventListener('pointermove',function(ev){if(ev.buttons||ev.pointerType==='mouse')move(ev)});c.addEventListener('touchstart',function(ev){if(ev.touches&&ev.touches[0])move(ev.touches[0])},{passive:true})}
  function drawInspect(g,result,rows,q,w,h,pad,p,canvasId){var st=ensureInspectState(canvasId,result,rows);st.geom={pad:pad,w:w,h:h,t0:result.start.getTime(),t1:result.end.getTime()};if(!st.moved){updateInspect(canvasId,result,null,0,rows.length);return}var idx=Math.max(0,Math.min(rows.length-1,st.index)),r=rows[idx],x=p.X(r),y=p.Y(val(r));g.save();g.strokeStyle='rgba(0,255,255,.72)';g.lineWidth=1*q;g.setLineDash([4*q,4*q]);g.beginPath();g.moveTo(x,pad.top);g.lineTo(x,h-pad.bottom);g.stroke();g.setLineDash([]);g.fillStyle='#00ffff';g.shadowColor='rgba(0,255,255,.75)';g.shadowBlur=7*q;g.beginPath();g.arc(x,y,4*q,0,Math.PI*2);g.fill();g.shadowBlur=0;var right=x>w/2,tx=right?Math.max(pad.left+150*q,x-18*q):Math.min(w-pad.right-150*q,x+18*q),ty=Math.max(pad.top+58*q,Math.min(h-pad.bottom-16*q,y-28*q));pointer(g,{x:x,y:y},q,tx,ty);eventBox(g,['SELECTED',fmt(val(r),1)+' MWh',niceDate(tm(r))],q,tx,ty,right?'right':'left');g.restore();updateInspect(canvasId,result,r,idx,rows.length)}
  function renderTo(canvasId,result){var canvas=document.getElementById(canvasId);if(!canvas)return;lastResult=result;ensureInspectControls(canvasId,result);attachInspectEvents(canvasId);var rows=rowsOf(result),ctx=canvas.getContext('2d'),box=canvas.getBoundingClientRect(),q=window.devicePixelRatio||1,isFull=canvasId==='solar-daily-mwh-fullscreen-canvas',cssW=Math.max(320,Math.floor(box.width||canvas.clientWidth||600)),cssH=Math.max(isFull?420:520,Math.floor(box.height||canvas.clientHeight||(isFull?720:560))),w=Math.floor(cssW*q),h=Math.floor(cssH*q);canvas.width=w;canvas.height=h;ctx.fillStyle='#05070c';ctx.fillRect(0,0,w,h);ctx.font='900 '+(cssW<520?11:15)*q+'px Courier New';ctx.fillStyle='#00ffff';var chartTitle=(result.technology||'Solar').toUpperCase()+' DAILY MWh · '+(result.sourceLabel||'PVLive stored energy');ctx.fillText(chartTitle,18*q,28*q,w-36*q);if(!rows.length){ctx.fillStyle='#9aa3b6';ctx.font=13*q+'px Courier New';ctx.fillText('Awaiting selected daily MWh data.',18*q,90*q);return}var pad=isFull?(cssW>cssH?{left:72*q,right:44*q,top:72*q,bottom:58*q}:{left:78*q,right:38*q,top:96*q,bottom:170*q}):{left:(cssW<520?86:96)*q,right:(cssW<520?48:72)*q,top:76*q,bottom:(cssW<620?150:116)*q},t0=result.start.getTime(),t1=result.end.getTime(),scale=mm(rows),p=points(w,h,pad,scale,t0,t1);drawTicks(ctx,w,h,q,scale,pad,t0,t1);drawSeasonKey(ctx,q,pad);drawSeasonLine(ctx,rows,p,q);var s=stats(rows);if(s){[[s.hi,s.hiValue,'HIGH'],[s.lo,s.loValue,'LOW']].forEach(function(it){ctx.fillStyle='#ff3333';ctx.shadowColor='rgba(0,255,255,.85)';ctx.shadowBlur=8*q;ctx.beginPath();ctx.arc(p.X(it[0]),p.Y(it[1]),5*q,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0});callout(ctx,'HIGH',s.hiValue,s.hiDate,p.X(s.hi),p.Y(s.hiValue),q,w,h,pad);callout(ctx,'LOW',s.loValue,s.loDate,p.X(s.lo),p.Y(s.loValue),q,w,h,pad);drawInspect(ctx,result,rows,q,w,h,pad,p,canvasId);drawSummary(ctx,s,q,w,h,pad,isFull)}}
  function render(canvas,result){if(!canvas||!canvas.id)return;renderTo(canvas.id,result)}
  function redrawFullscreen(result){if(result)renderTo('solar-daily-mwh-fullscreen-canvas',result);else if(lastResult)renderTo('solar-daily-mwh-fullscreen-canvas',lastResult)}
  return{render:render,redrawFullscreen:redrawFullscreen};
})();
