window.V6RenderSolarDailyMwhChart=(function(){
  function fmt(n,d){return n==null||isNaN(Number(n))?'—':Number(n).toLocaleString('en-GB',{minimumFractionDigits:d,maximumFractionDigits:d})}
  function niceDate(v){var d=v instanceof Date?v:new Date(String(v).replace(' ','T'));return isNaN(d.getTime())?'—':d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}
  function dateLabel(t,span){var d=new Date(t);return span>45*86400000?d.toLocaleDateString('en-GB',{month:'short',year:'numeric'}):d.toLocaleDateString('en-GB',{day:'2-digit',month:'short'})}
  function val(r){return Number(r.mwh)}
  function tm(r){return r.date+'T12:00:00Z'}
  function stats(rows){var hi=null,lo=null,total=0,n=0;rows.forEach(function(r){var v=val(r);if(isNaN(v))return;total+=v;n++;if(!hi||v>val(hi))hi=r;if(!lo||v<val(lo))lo=r});return hi&&lo?{hi:hi,lo:lo,hiValue:val(hi),loValue:val(lo),hiDate:niceDate(tm(hi)),loDate:niceDate(tm(lo)),mean:total/n,total:total,range:niceDate(tm(rows[0]))+' to '+niceDate(tm(rows[rows.length-1]))}:null}
  function mm(rows){var hi=1;rows.forEach(function(r){var v=val(r);if(!isNaN(v)&&v>hi)hi=v});return{lo:0,hi:hi*1.10}}
  function step(span){var raw=span/5,p=Math.pow(10,Math.floor(Math.log10(Math.max(raw,1)))),n=raw/p;if(n<=1)return p;if(n<=2)return 2*p;if(n<=5)return 5*p;return 10*p}
  function points(w,h,pad,scale,t0,t1){var pw=w-pad.left-pad.right,ph=h-pad.top-pad.bottom;return{X:function(r){var t=new Date(tm(r)).getTime();return pad.left+((t-t0)/(t1-t0))*pw},Y:function(v){return pad.top+((scale.hi-v)/(scale.hi-scale.lo))*ph}}}
  function drawTicks(g,w,h,q,scale,pad,t0,t1){var st=step(scale.hi-scale.lo),span=t1-t0;g.save();g.font=(w/q<520?9:11)*q+'px Courier New';for(var v=0;v<=scale.hi+st*.5;v+=st){var y=pad.top+((scale.hi-v)/(scale.hi-scale.lo))*(h-pad.top-pad.bottom);g.fillStyle='#d8deeb';g.textAlign='left';g.fillText(fmt(v,0)+' MWh',8*q,y+4*q);g.strokeStyle='rgba(255,255,255,.055)';g.beginPath();g.moveTo(pad.left,y);g.lineTo(w-pad.right,y);g.stroke()}g.strokeStyle='rgba(255,255,255,.26)';g.beginPath();g.moveTo(pad.left,h-pad.bottom);g.lineTo(w-pad.right,h-pad.bottom);g.stroke();g.fillStyle='#d8deeb';g.textAlign='left';g.fillText(dateLabel(t0,span),pad.left,h-pad.bottom+24*q);g.textAlign='right';g.fillText(dateLabel(t1,span),w-pad.right,h-pad.bottom+24*q);g.restore()}
  function callout(g,label,value,date,x,y,q,w,h,pad){var lines=[label,fmt(value,1)+' MWh',date],fontSize=(w/q<520?10:13)*q,lh=17*q,padb=8*q,bw=0;g.save();g.font='900 '+fontSize+'px Courier New';lines.forEach(function(t){bw=Math.max(bw,g.measureText(t).width)});var boxW=bw+padb*2,boxH=lines.length*lh+padb*2,preferRight=x<w/2,boxX=preferRight?x+22*q:x-22*q-boxW,boxY=label==='HIGH'?y-boxH-26*q:y-boxH-20*q;if(boxY<pad.top+8*q)boxY=y+24*q;boxX=Math.max(pad.left,Math.min(w-pad.right-boxW,boxX));boxY=Math.max(pad.top+8*q,Math.min(h-pad.bottom-boxH-8*q,boxY));var lineX=boxX+(preferRight?0:boxW),lineY=boxY+boxH/2;g.strokeStyle='#ff3333';g.lineWidth=1.35*q;g.shadowColor='rgba(0,255,255,.55)';g.shadowBlur=7*q;g.beginPath();g.moveTo(x,y);g.lineTo(lineX,lineY);g.stroke();g.fillStyle='rgba(5,7,12,.86)';g.strokeStyle='rgba(0,255,255,.48)';g.shadowBlur=0;g.beginPath();g.roundRect(boxX,boxY,boxW,boxH,7*q);g.fill();g.stroke();g.fillStyle='#ff3333';g.textAlign='left';lines.forEach(function(t,i){g.fillText(t,boxX+padb,boxY+padb+(i+1)*lh-4*q)});g.restore()}
  function drawSummary(g,s,q,w,h,pad){var mobile=w/q<620,x=pad.left,bw=w-pad.left-pad.right,y=h-(mobile?116:72)*q,rows=mobile?2:1,cols=mobile?2:4,cellH=mobile?46*q:52*q,col=bw/cols;g.save();g.fillStyle='rgba(5,7,12,.92)';g.strokeStyle='rgba(0,255,255,.42)';g.beginPath();g.roundRect(x,y,bw,rows*cellH,9*q);g.fill();g.stroke();function cell(i,l,v,sub,c){var r=mobile?Math.floor(i/2):0,cc=mobile?i%2:i,cx=x+cc*col+12*q,cy=y+r*cellH;g.fillStyle='#9aa3b6';g.font='900 '+(mobile?8:9)*q+'px Courier New';g.fillText(l,cx,cy+16*q);g.fillStyle=c;g.font='900 '+(mobile?9:12)*q+'px Courier New';g.fillText(v,cx,cy+32*q);g.fillStyle='#d8deeb';g.font=(mobile?7:8.5)*q+'px Courier New';g.fillText(sub,cx,cy+45*q)}cell(0,'HIGH DAY',fmt(s.hiValue,1)+' MWh',s.hiDate,'#ff4444');cell(1,'LOW DAY',fmt(s.loValue,1)+' MWh',s.loDate,'#ff4444');cell(2,'MEAN DAILY',fmt(s.mean,1)+' MWh',s.range,'#00ffff');cell(3,'TOTAL SHOWN',fmt(s.total/1000000,2)+' TWh','Selected range','#f5c518');g.restore()}
  function render(canvas,result){var rows=(result.rows||[]).filter(function(r){return r&&r.mwh!=null&&!isNaN(Number(r.mwh))});var ctx=canvas.getContext('2d'),box=canvas.getBoundingClientRect(),q=window.devicePixelRatio||1,cssW=Math.max(320,Math.floor(box.width||canvas.clientWidth||600)),cssH=Math.max(520,Math.floor(box.height||canvas.clientHeight||560)),w=Math.floor(cssW*q),h=Math.floor(cssH*q);canvas.width=w;canvas.height=h;ctx.fillStyle='#05070c';ctx.fillRect(0,0,w,h);ctx.font='900 '+(cssW<520?11:15)*q+'px Courier New';ctx.fillStyle='#00ffff';ctx.fillText('SOLAR DAILY MWh · PVLive stored energy',18*q,28*q,w-36*q);if(!rows.length){ctx.fillStyle='#9aa3b6';ctx.font=13*q+'px Courier New';ctx.fillText('Awaiting Solar daily MWh data.',18*q,90*q);return}var pad={left:(cssW<520?86:96)*q,right:(cssW<520?48:72)*q,top:76*q,bottom:(cssW<620?150:116)*q},t0=result.start.getTime(),t1=result.end.getTime(),scale=mm(rows),p=points(w,h,pad,scale,t0,t1),c='#f5c518';drawTicks(ctx,w,h,q,scale,pad,t0,t1);ctx.save();ctx.strokeStyle=c;ctx.lineWidth=2.15*q;ctx.shadowColor=c;ctx.shadowBlur=9*q;ctx.beginPath();rows.forEach(function(r,i){var x=p.X(r),y=p.Y(val(r));if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y)});ctx.stroke();ctx.restore();var s=stats(rows);if(s){[[s.hi,s.hiValue,'HIGH'],[s.lo,s.loValue,'LOW']].forEach(function(it){ctx.fillStyle='#ff3333';ctx.shadowColor='rgba(0,255,255,.85)';ctx.shadowBlur=8*q;ctx.beginPath();ctx.arc(p.X(it[0]),p.Y(it[1]),5*q,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0});callout(ctx,'HIGH',s.hiValue,s.hiDate,p.X(s.hi),p.Y(s.hiValue),q,w,h,pad);callout(ctx,'LOW',s.loValue,s.loDate,p.X(s.lo),p.Y(s.loValue),q,w,h,pad);drawSummary(ctx,s,q,w,h,pad)}}
  return{render:render};
})();
