import requests
import json
import time

def fetch_substations(filename="grid_substations.geojson"):
    print("\n⚡ Fetching UK Major Substations (33kV to 400kV)...")
    
    # We use 'out center;' so if the substation is drawn as a polygon (way/relation), 
    # the server calculates the exact center point for us to use as a map marker.
    query = """
    [out:json][timeout:300];
    area(3600062149)->.uk;
    (
      node["power"="substation"]["voltage"~"400000|275000|220000|132000|66000|33000"](area.uk);
      way["power"="substation"]["voltage"~"400000|275000|220000|132000|66000|33000"](area.uk);
      relation["power"="substation"]["voltage"~"400000|275000|220000|132000|66000|33000"](area.uk);
    );
    out center;
    """
    
    url = "https://overpass-api.de/api/interpreter"
    
    for attempt in range(3):
        print(f"Attempt {attempt + 1} of 3...")
        response = requests.post(url, data={'data': query})
        
        if response.status_code == 200:
            print("✅ Substation Data successfully downloaded!")
            break
        elif response.status_code == 429:
            print("⚠️ Server busy, sleeping 60s...")
            time.sleep(60)
        else:
            print(f"❌ Error: {response.text[:100]}")
            return

    try:
        osm_data = response.json()
    except ValueError:
        print("❌ Failed to parse JSON.")
        return

    geojson = {"type": "FeatureCollection", "features": []}
    
    for element in osm_data.get('elements', []):
        # Nodes have direct lat/lon
        if element['type'] == 'node':
            lat = element.get('lat')
            lon = element.get('lon')
        # Ways and relations have a 'center' object generated by our query
        elif 'center' in element:
            lat = element['center'].get('lat')
            lon = element['center'].get('lon')
        else:
            continue
            
        if lat and lon:
            tags = element.get('tags', {})
            feature = {
                "type": "Feature",
                "properties": tags,
                "geometry": {
                    "type": "Point",
                    "coordinates": [lon, lat]
                }
            }
            geojson['features'].append(feature)
            
    with open(filename, 'w', encoding='utf-8') as f:
        json.dump(geojson, f)
        
    print(f"💾 Saved {len(geojson['features'])} substations to {filename}")

if __name__ == "__main__":
    fetch_substations()

