window.V6RenderCommodities=(function(){
  var oilChartState={rows:[],pad:54,dpr:1};
  function h(){return window.V6DomText}
  function fmt(v,d){return h().fmt(v,d)}
  function set(id,v){h().setText(id,v)}
  function sym(c){return c==='GBP'?'£':c==='EUR'?'€':'$'}
  function fmtMoney(v,c){return v==null||isNaN(Number(v))?'—':sym(c)+Number(v).toLocaleString('en-GB',{maximumFractionDigits:0})}
  function renderMetalCard(id,metal,data){var el=document.getElementById(id);if(!el)return;var usd=data[metal+'USDperTonne'],eur=data[metal+'EURperTonne'],gbp=data[metal+'GBPperTonne'];if(usd==null&&eur==null&&gbp==null){el.textContent='—';return}el.innerHTML='<span style="display:block">'+fmtMoney(usd,'USD')+' <span style="font-size:12px;color:#9aa3b6">USD/t</span></span>'+'<span style="display:block;font-size:16px;margin-top:4px;color:#00ffff">'+fmtMoney(eur,'EUR')+' <span style="font-size:11px;color:#9aa3b6">EUR/t</span></span>'+'<span style="display:block;font-size:16px;margin-top:2px;color:#f5f7fb">'+fmtMoney(gbp,'GBP')+' <span style="font-size:11px;color:#9aa3b6">GBP/t</span></span>'}
  function renderFuelBreakdown(oil,latest){var el=document.getElementById('fuel-breakdown');if(!el)return;var brent=oil&&oil.brentUSDperBarrel,petrol=latest&&latest.petrolPencePerLitre;var stamp=oil&&oil.updatedDisplayUTC?' Commodity sync: '+oil.updatedDisplayUTC+'.':'';if(brent==null||petrol==null){el.textContent='Awaiting Brent crude and DESNZ fuel price feed.'+stamp;return}var gbpUsd=(oil.fx&&oil.fx.gbpUSD)||1.27,litres=158.987,duty=52.95,vatRate=0.20;var crudePpl=(Number(brent)/gbpUsd/litres)*100,preVat=Number(petrol)/(1+vatRate),vat=Number(petrol)-preVat,spread=preVat-duty-crudePpl;el.innerHTML='Brent proxy: $'+fmt(brent,2)+'/bbl divided by FX '+fmt(gbpUsd,4)+' and 159 litres equals about '+fmt(crudePpl,1)+'p/l crude input. Petrol pump: '+fmt(petrol,2)+'p/l. VAT at 20%: '+fmt(vat,1)+'p/l. Fuel duty assumption: '+fmt(duty,2)+'p/l. Implied refining, logistics, wholesale and retail spread: '+fmt(spread,1)+'p/l. Week: '+(latest.week||'not stated')+'.'+stamp}
  function renderEvPrices(ev){var ops=(ev&&ev.operators)||[],rapid=[],ultra=[];ops.forEach(function(o){if(o.rapidPencePerKWh!=null)rapid.push(Number(o.rapidPencePerKWh));if(o.ultraRapidPencePerKWh!=null)ultra.push(Number(o.ultraRapidPencePerKWh))});set('ev-rapid-price',rapid.length?fmt(rapid.reduce(function(a,b){return a+b},0)/rapid.length,1)+'p':'—');set('ev-ultra-price',ultra.length?fmt(ultra.reduce(function(a,b){return a+b},0)/ultra.length,1)+'p':'—')}
  function rangeCutoff(range){var d=new Date();if(range==='7d')d.setDate(d.getDate()-7);else if(range==='1m')d.setMonth(d.getMonth()-1);else if(range==='3m')d.setMonth(d.getMonth()-3);else if(range==='6m')d.setMonth(d.getMonth()-6);else if(range==='9m')d.setMonth(d.getMonth()-9);else if(range==='1y')d.setFullYear(d.getFullYear()-1);else if(range==='5y')d.setFullYear(d.getFullYear()-5);else if(range==='10y')d.setFullYear(d.getFullYear()-10);else if(range==='25y')d.setFullYear(d.getFullYear()-25);else return null;return d}
  function oilStats(rows){var vals=[];rows.forEach(function(p){if(p.brentUSDperBarrel)vals.push(p.brentUSDperBarrel);if(p.wtiUSDperBarrel)vals.push(p.wtiUSDperBarrel)});var el=document.getElementById('oil-stats');if(!el)return;if(!vals.length){el.innerHTML='';return}var high=Math.max.apply(null,vals),low=Math.min.apply(null,vals),avg=vals.reduce(function(a,b){return a+b},0)/vals.length;var vol=avg?Math.sqrt(vals.reduce(function(a,b){return a+Math.pow(b-avg,2)},0)/vals.length)/avg*100:0;el.innerHTML=[['High','$'+fmt(high,2)],['Low','$'+fmt(low,2)],['Average','$'+fmt(avg,2)],['Volatility',fmt(vol,1)+'%']].map(function(x){return '<div class="oil-stat"><div class="oil-stat-label">'+x[0]+'</div><div class="oil-stat-value">'+x[1]+'</div></div>'}).join('')}
  function drawOilTrend(geo){var canvas=document.getElementById('oil-trend-canvas');if(!canvas||!geo||!Array.isArray(geo.features))return;var ctx=canvas.getContext('2d'),range=document.getElementById('oil-range').value;var rows=geo.features.map(function(f){return f.properties||{}}).filter(function(p){return p.date&&(p.brentUSDperBarrel||p.wtiUSDperBarrel)});var cutoff=rangeCutoff(range);if(cutoff)rows=rows.filter(function(p){return new Date(p.date)>=cutoff});var rect=canvas.getBoundingClientRect(),dpr=window.devicePixelRatio||1;canvas.width=Math.max(340,Math.floor((rect.width||900)*dpr));canvas.height=Math.max(260,Math.floor((rect.height||300)*dpr));var w=canvas.width,hgt=canvas.height,pad=54*dpr,right=28*dpr;ctx.clearRect(0,0,w,hgt);ctx.fillStyle='#070a10';ctx.fillRect(0,0,w,hgt);if(rows.length<2){ctx.fillStyle='#a6adbb';ctx.font=(14*dpr)+'px Courier New';ctx.fillText('Waiting for oil history data',pad,42*dpr);oilStats([]);return}var vals=[];rows.forEach(function(p){if(p.brentUSDperBarrel)vals.push(p.brentUSDperBarrel);if(p.wtiUSDperBarrel)vals.push(p.wtiUSDperBarrel)});var min=Math.min.apply(null,vals),max=Math.max.apply(null,vals);if(max===min)max=min+1;function x(i){return pad+(i/(rows.length-1))*(w-pad-right)}function y(v){return hgt-pad-((v-min)/(max-min))*(hgt-pad*1.85)}ctx.strokeStyle='#252b36';ctx.lineWidth=1*dpr;ctx.fillStyle='#a6adbb';ctx.font=(16*dpr)+'px Courier New';for(var g=0;g<5;g++){var value=max-(g*(max-min)/4),yy=y(value);ctx.beginPath();ctx.moveTo(pad,yy);ctx.lineTo(w-right,yy);ctx.stroke();ctx.fillText('$'+fmt(value,0),8*dpr,yy+4*dpr)}function line(field,colour){ctx.strokeStyle=colour;ctx.lineWidth=2*dpr;ctx.beginPath();var started=false;rows.forEach(function(p,i){var v=p[field];if(!v)return;if(!started){ctx.moveTo(x(i),y(v));started=true}else ctx.lineTo(x(i),y(v))});ctx.stroke()}line('brentUSDperBarrel','#ff9900');line('wtiUSDperBarrel','#00ffff');ctx.fillStyle='#a6adbb';ctx.font=(12*dpr)+'px Courier New';ctx.fillText('Brent',pad,18*dpr);ctx.fillStyle='#ff9900';ctx.fillRect(pad+46*dpr,10*dpr,18*dpr,4*dpr);ctx.fillStyle='#a6adbb';ctx.fillText('WTI',pad+78*dpr,18*dpr);ctx.fillStyle='#00ffff';ctx.fillRect(pad+112*dpr,10*dpr,18*dpr,4*dpr);oilChartState={rows:rows,pad:pad,dpr:dpr};oilStats(rows);bindOilTooltip()}
  function bindOilTooltip(){var canvas=document.getElementById('oil-trend-canvas'),tip=document.getElementById('oil-tooltip');if(!canvas||!tip||canvas.dataset.tipBound)return;canvas.dataset.tipBound='1';function show(e){var rect=canvas.getBoundingClientRect(),clientX=(e.touches&&e.touches[0]?e.touches[0].clientX:e.clientX),rows=oilChartState.rows||[];if(!rows.length)return;var pad=(oilChartState.pad||54)/(oilChartState.dpr||1),idx=Math.max(0,Math.min(rows.length-1,Math.round((clientX-rect.left-pad)/(rect.width-pad-28)*(rows.length-1))));var p=rows[idx];tip.innerHTML='<strong>'+p.date+'</strong><br>Brent: '+(p.brentUSDperBarrel?'$'+fmt(p.brentUSDperBarrel,2):'—')+' USD/bbl<br>WTI: '+(p.wtiUSDperBarrel?'$'+fmt(p.wtiUSDperBarrel,2):'—')+' USD/bbl';tip.style.display='block';tip.style.left=Math.min(rect.width-190,Math.max(8,clientX-rect.left+12))+'px';tip.style.top='42px'}function hide(){tip.style.display='none'}canvas.addEventListener('mousemove',show);canvas.addEventListener('touchmove',show,{passive:true});canvas.addEventListener('mouseleave',hide);canvas.addEventListener('touchend',hide)}
  function render(data,fuel,ev,oilHistory){data=data||{};fuel=fuel||{};set('brent-price',data.brentUSDperBarrel==null?'—':'USD '+fmt(data.brentUSDperBarrel,2));set('wti-price',data.wtiUSDperBarrel==null?'—':'USD '+fmt(data.wtiUSDperBarrel,2));renderMetalCard('copper-price','copper',data);renderMetalCard('aluminium-price','aluminium',data);var latest=fuel.latest||{};set('petrol-price',latest.petrolPencePerLitre==null?'—':fmt(latest.petrolPencePerLitre,2)+'p');set('diesel-price',latest.dieselPencePerLitre==null?'—':fmt(latest.dieselPencePerLitre,2)+'p');renderFuelBreakdown(data,latest);renderEvPrices(ev||{});if(oilHistory){window.__v6OilHistoryCache=oilHistory;drawOilTrend(oilHistory)}var oilRange=document.getElementById('oil-range');if(oilRange&&!oilRange.dataset.bound){oilRange.dataset.bound='1';oilRange.addEventListener('change',function(){if(window.__v6OilHistoryCache)drawOilTrend(window.__v6OilHistoryCache)})}}
  return{render:render,drawOilTrend:drawOilTrend};
})();
