window.V6RenderPriceChart=(function(){
  var lastResult=null;
  function fmt(n,d){return n==null||isNaN(Number(n))?'—':Number(n).toLocaleString('en-GB',{minimumFractionDigits:d,maximumFractionDigits:d})}
  function price(r){return Number(r.price!=null?r.price:r.priceGBPperMWh)}
  function time(r){return r.time||r.priceTimeUTC}
  function seasonName(t){var m=new Date(t).getUTCMonth()+1;if(m===12||m<=2)return'Winter';if(m>=3&&m<=5)return'Spring';if(m>=6&&m<=8)return'Summer';return'Autumn'}
  function seasonColor(t){var s=seasonName(t);if(s==='Winter')return'#00ffff';if(s==='Spring')return'#00ff88';if(s==='Summer')return'#ffcc00';return'#c79245'}
  function values(result){if(result.mode==='daily')return result.rows.flatMap(function(r){return [r.high,r.low,r.average].filter(function(v){return v!=null&&!isNaN(Number(v))}).map(Number)});return result.rows.map(price).filter(function(v){return !isNaN(v)})}
  function stats(result){var rows=result.rows;if(!rows.length)return null;if(result.mode==='daily'){var hi=rows[0],lo=rows[0],sum=0,c=0;rows.forEach(function(r){if(r.average!=null){sum+=Number(r.average);c++}if(Number(r.high)>Number(hi.high))hi=r;if(Number(r.low)<Number(lo.low))lo=r});return{hi:hi,lo:lo,avg:c?sum/c:null,hiValue:Number(hi.high),loValue:Number(lo.low),hiTime:hi.date+' '+(hi.highAt||''),loTime:lo.date+' '+(lo.lowAt||'')}}var h=rows[0],l=rows[0],s=0;rows.forEach(function(r){var v=price(r);s+=v;if(v>price(h))h=r;if(v<price(l))l=r});return{hi:h,lo:l,avg:s/rows.length,hiValue:price(h),loValue:price(l),hiTime:new Date(time(h)).toLocaleString('en-GB'),loTime:new Date(time(l)).toLocaleString('en-GB')}}
  function minMax(v){var lo=0,hi=0;v.forEach(function(x){if(x<lo)lo=x;if(x>hi)hi=x});if(lo===hi)hi=lo+1;var m=(hi-lo)*.06;return{lo:lo-m,hi:hi+m}}
  function step(span){var raw=span/10,p=Math.pow(10,Math.floor(Math.log10(Math.max(raw,1)))),n=raw/p;if(n<=1)return p;if(n<=2)return 2*p;if(n<=5)return 5*p;return 10*p}
  function dateLabel(t,span){return span>45*86400000?new Date(t).toLocaleDateString('en-GB',{month:'long',year:'numeric'}):new Date(t).toLocaleDateString('en-GB')}
  function drawSeasonBands(g,w,h,q,pad,t0,t1){var span=t1-t0;if(span<20*86400000)return;var start=new Date(t0);start.setUTCDate(1);start.setUTCHours(0,0,0,0);var plotW=w-pad.left-pad.right,plotH=h-pad.top-pad.bottom;for(var d=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth(),1));d.getTime()<t1;d.setUTCMonth(d.getUTCMonth()+1)){var a=Math.max(d.getTime(),t0);var b=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,1)).getTime();b=Math.min(b,t1);if(b<=a)continue;var x=pad.left+((a-t0)/(t1-t0))*plotW;var x2=pad.left+((b-t0)/(t1-t0))*plotW;var col=seasonColor(d.toISOString());g.save();g.fillStyle=col;g.globalAlpha=.035;g.fillRect(x,pad.top,Math.max(1,x2-x),plotH);g.globalAlpha=.16;g.strokeStyle=col;g.lineWidth=.6*q;g.beginPath();g.moveTo(x,pad.top);g.lineTo(x,h-pad.bottom);g.stroke();g.restore()}}
  function drawAxes(g,w,h,q,mm,pad,t0,t1){var st=step(mm.hi-mm.lo),start=Math.ceil(mm.lo/st)*st,span=t1-t0;g.font=11*q+'px Courier New';for(var v=start;v<=mm.hi+st*.5;v+=st){var y=pad.top+((mm.hi-v)/(mm.hi-mm.lo))*(h-pad.top-pad.bottom);g.strokeStyle='rgba(255,255,255,.18)';g.beginPath();g.moveTo(pad.left,y);g.lineTo(w-pad.right,y);g.stroke();g.fillStyle='#f5f7fb';g.textAlign='left';g.fillText('£'+fmt(v,0).replace('-0','0'),8*q,y+4*q)}g.save();g.strokeStyle='rgba(255,255,255,.22)';g.lineWidth=1*q;g.beginPath();g.moveTo(pad.left,h-pad.bottom);g.lineTo(w-pad.right,h-pad.bottom);g.stroke();g.fillStyle='#f5f7fb';g.font=11*q+'px Courier New';g.textAlign='left';g.fillText(dateLabel(t0,span),pad.left,h-pad.bottom+24*q);g.textAlign='right';g.fillText(dateLabel(t1,span),w-pad.right,h-pad.bottom+24*q);g.restore();g.textAlign='left'}
  function drawKey(g,q,pad){var items=[['Winter','#00ffff'],['Spring','#00ff88'],['Summer','#ffcc00'],['Autumn','#c79245']],x=pad.left,y=pad.top-24*q;g.save();g.font=9*q+'px Courier New';items.forEach(function(it){g.fillStyle=it[1];g.shadowColor=it[1];g.shadowBlur=4*q;g.fillRect(x,y-7*q,8*q,8*q);g.shadowBlur=0;g.fillStyle='#9aa3b6';g.fillText(it[0],x+12*q,y);x+=58*q});g.restore()}
  function drawBox(g,q,x,y,align,lines){var pad=8*q,lh=18*q,w=0;g.save();g.font='900 '+14*q+'px Courier New';lines.forEach(function(t){w=Math.max(w,g.measureText(t).width)});var xx=align==='right'?x-w-pad*2:x;g.fillStyle='rgba(5,7,12,.78)';g.strokeStyle='rgba(0,255,255,.35)';g.shadowColor='rgba(0,255,255,.24)';g.shadowBlur=8*q;g.beginPath();g.roundRect(xx,y-lines.length*lh-pad,w+pad*2,lines.length*lh+pad*2,6*q);g.fill();g.stroke();g.shadowBlur=0;g.fillStyle='#ff3333';g.textAlign=align;lines.forEach(function(t,i){g.fillText(t,x,y-(lines.length-1-i)*lh)});g.restore()}
  function pence(v){return fmt(Number(v)/10,2)}
  function set(id,v){var e=document.getElementById(id);if(e)e.textContent=v}
  function drawSummary(g,s,q,w,h,pad){var mobile=(w/q)<720,y=h-(mobile?58:44)*q;g.save();g.fillStyle='rgba(5,7,12,.72)';g.strokeStyle='rgba(0,255,255,.26)';g.lineWidth=1*q;g.beginPath();g.roundRect(pad.left,y-(mobile?34:26)*q,w-pad.left-pad.right,(mobile?72:46)*q,6*q);g.fill();g.stroke();g.fillStyle='#f5f7fb';g.textAlign='center';var mid=w/2;if(mobile){g.font='900 '+8.8*q+'px Courier New';g.fillText('HIGH  '+pence(s.hiValue)+'p/kWh   £'+fmt(s.hiValue,2)+'/MWh',mid,y-14*q);g.fillText('AVG   '+pence(s.avg)+'p/kWh   £'+fmt(s.avg,2)+'/MWh',mid,y+6*q);g.fillText('LOW   '+pence(s.loValue)+'p/kWh   £'+fmt(s.loValue,2)+'/MWh',mid,y+26*q)}else{g.font='900 '+10*q+'px Courier New';g.fillText('HIGH '+pence(s.hiValue)+'p/kWh (£'+fmt(s.hiValue,2)+'/MWh)     AVG '+pence(s.avg)+'p/kWh (£'+fmt(s.avg,2)+'/MWh)     LOW '+pence(s.loValue)+'p/kWh (£'+fmt(s.loValue,2)+'/MWh)',mid,y)}g.restore()}
  function decimateRows(rows,limit){if(!rows||rows.length<=limit)return rows||[];var out=[],bucket=Math.ceil(rows.length/limit);for(var i=0;i<rows.length;i+=bucket){var slice=rows.slice(i,i+bucket),hi=slice[0],lo=slice[0];slice.forEach(function(r){if(price(r)>price(hi))hi=r;if(price(r)<price(lo))lo=r});if(new Date(time(lo))<new Date(time(hi))){out.push(lo);if(hi!==lo)out.push(hi)}else{out.push(hi);if(hi!==lo)out.push(lo)}}return out.sort(function(a,b){return new Date(time(a))-new Date(time(b))})}
  function renderTo(canvasId,result){var c=document.getElementById(canvasId);if(!c)return;var q=window.devicePixelRatio||1,r=c.getBoundingClientRect();c.width=Math.max(320,Math.floor((r.width||1200)*q));c.height=Math.max(360,Math.floor((r.height||720)*q));var g=c.getContext('2d'),w=c.width,h=c.height,pad={left:74*q,right:24*q,top:96*q,bottom:214*q};g.clearRect(0,0,w,h);g.fillStyle='#05070c';g.fillRect(0,0,w,h);if(!result||!result.rows||result.rows.length<2){g.fillStyle='#00ffff';g.font=14*q+'px Courier New';g.fillText('No records in selected range.',pad.left,42*q);return}var vals=values(result),mm=minMax(vals),t0=result.start.getTime(),t1=result.end.getTime();drawSeasonBands(g,w,h,q,pad,t0,t1);drawAxes(g,w,h,q,mm,pad,t0,t1);drawKey(g,q,pad);function X(row){var t=result.mode==='daily'?new Date(row.date+'T12:00:00Z').getTime():new Date(time(row)).getTime();return pad.left+((t-t0)/(t1-t0))*(w-pad.left-pad.right)}function Y(v){return pad.top+((mm.hi-v)/(mm.hi-mm.lo))*(h-pad.top-pad.bottom)}
    if(result.mode==='daily'){['average','high','low'].forEach(function(k){g.save();g.lineWidth=(k==='average'?2.4:1.6)*q;g.setLineDash(k==='average'?[]:(k==='high'?[5*q,4*q]:[2*q,5*q]));g.lineCap='round';g.lineJoin='round';for(var i=1;i<result.rows.length;i++){var a=result.rows[i-1],b=result.rows[i];if(a[k]==null||b[k]==null||isNaN(Number(a[k]))||isNaN(Number(b[k])))continue;var col=seasonColor(b.date+'T12:00:00Z');g.strokeStyle=col;g.shadowColor=col;g.shadowBlur=4*q;g.beginPath();g.moveTo(X(a),Y(Number(a[k])));g.lineTo(X(b),Y(Number(b[k])));g.stroke()}g.restore()})}else{var lineRows=decimateRows(result.rows,Math.max(900,Math.floor((w/q)*1.8)));g.save();g.lineWidth=2.1*q;g.lineCap='round';g.lineJoin='round';for(var j=1;j<lineRows.length;j++){var aa=lineRows[j-1],bb=lineRows[j],col2=seasonColor(time(bb));g.strokeStyle=col2;g.shadowColor=col2;g.shadowBlur=5*q;g.beginPath();g.moveTo(X(aa),Y(price(aa)));g.lineTo(X(bb),Y(price(bb)));g.stroke()}g.restore()}
    var s=stats(result);if(s){var hx=X(s.hi),hy=Y(s.hiValue),lx=X(s.lo),ly=Y(s.loValue);g.save();g.fillStyle='#ff3333';g.shadowColor='rgba(0,255,255,.8)';g.shadowBlur=8*q;g.beginPath();g.arc(hx,hy,5*q,0,Math.PI*2);g.fill();g.beginPath();g.arc(lx,ly,5*q,0,Math.PI*2);g.fill();g.restore();drawBox(g,q,hx<w/2?hx+18*q:hx-18*q,Math.max(pad.top+54*q,hy-24*q),hx<w/2?'left':'right',['HIGH','£'+fmt(s.hiValue,2)+'/MWh',s.hiTime]);drawBox(g,q,lx<w/2?lx+18*q:lx-18*q,Math.min(h-pad.bottom-28*q,ly+54*q),lx<w/2?'left':'right',['LOW','£'+fmt(s.loValue,2)+'/MWh',s.loTime]);drawSummary(g,s,q,w,h,pad);set('ph-latest-price','£'+fmt(s.avg,2)+'/MWh');set('ph-row-count',result.rows.length.toLocaleString('en-GB'));set('ph-source','Elexon BMRS');set('price-history-range-status',new Date(result.start).toLocaleDateString('en-GB')+' to '+new Date(result.end).toLocaleDateString('en-GB')+' | '+result.rows.length.toLocaleString('en-GB')+' points')}
  }
  function render(result){lastResult=result;renderTo('price-history-canvas',result);var o=document.getElementById('price-history-fullscreen-overlay');if(o&&o.classList.contains('open'))renderTo('price-history-fullscreen-canvas',result)}
  function redrawFullscreen(){if(lastResult)renderTo('price-history-fullscreen-canvas',lastResult)}
  return{render:render,redrawFullscreen:redrawFullscreen};
})();