window.V6RenderPriceChart=(function(){
  var lastResult=null;
  function fmt(n,d){return n==null||isNaN(Number(n))?'—':Number(n).toLocaleString('en-GB',{minimumFractionDigits:d,maximumFractionDigits:d})}
  function price(r){return Number(r.price!=null?r.price:r.priceGBPperMWh)}
  function time(r){return r.time||r.priceTimeUTC}
  function niceDate(v){var d=v instanceof Date?v:new Date(String(v).replace(' ','T')+'Z');if(isNaN(d.getTime()))d=new Date(v);return isNaN(d.getTime())?'—':d.toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}
  function niceClock(v){var s=String(v||'');var m=s.match(/(\d{2}:\d{2})/);return m?m[1]:''}
  function seasonName(t){var m=new Date(t).getUTCMonth()+1;if(m===12||m<=2)return'Winter';if(m>=3&&m<=5)return'Spring';if(m>=6&&m<=8)return'Summer';return'Autumn'}
  function seasonColor(t){var s=seasonName(t);if(s==='Winter')return'#00ffff';if(s==='Spring')return'#00ff88';if(s==='Summer')return'#ffcc00';return'#c79245'}
  function actualValue(r,mode){return mode==='daily'?Number(r.average):price(r)}
  function forecastValue(r){return Number(r.forecast!=null?r.forecast:r.average)}
  function values(result){var out=[];(result.rows||[]).forEach(function(r){if(result.mode==='daily'){['average','high','low'].forEach(function(k){var v=Number(r[k]);if(!isNaN(v))out.push(v)})}else{var v=price(r);if(!isNaN(v))out.push(v)}});(result.forecastRows||[]).forEach(function(r){var f=forecastValue(r);if(!isNaN(f))out.push(f)});return out}
  function stats(result){var rows=result.rows||[];if(!rows.length)return null;if(result.mode==='daily'){var valid=rows.filter(function(r){return r.average!=null&&r.high!=null&&r.low!=null&&!isNaN(Number(r.average))&&!isNaN(Number(r.high))&&!isNaN(Number(r.low))});if(!valid.length)return null;var hi=valid[0],lo=valid[0],sum=0;valid.forEach(function(r){sum+=Number(r.average);if(Number(r.high)>Number(hi.high))hi=r;if(Number(r.low)<Number(lo.low))lo=r});return{hi:hi,lo:lo,avg:sum/valid.length,hiValue:Number(hi.high),loValue:Number(lo.low),hiDate:niceDate(hi.date),loDate:niceDate(lo.date),hiClock:hi.highAt||'',loClock:lo.lowAt||'',avgDate:niceDate(result.start)+' to '+niceDate(result.end)}}var h=rows[0],l=rows[0],s=0;rows.forEach(function(r){var v=price(r);s+=v;if(v>price(h))h=r;if(v<price(l))l=r});return{hi:h,lo:l,avg:s/rows.length,hiValue:price(h),loValue:price(l),hiDate:niceDate(time(h)),loDate:niceDate(time(l)),hiClock:niceClock(time(h)),loClock:niceClock(time(l)),avgDate:niceDate(result.start)+' to '+niceDate(result.end)}}
  function minMax(v){var lo=0,hi=0;v.forEach(function(x){if(x<lo)lo=x;if(x>hi)hi=x});if(lo===hi)hi=lo+1;var m=Math.max((hi-lo)*.08,10);return{lo:lo-m,hi:hi+m}}
  function step(span){var raw=span/8,p=Math.pow(10,Math.floor(Math.log10(Math.max(raw,1)))),n=raw/p;if(n<=1)return p;if(n<=2)return 2*p;if(n<=5)return 5*p;return 10*p}
  function dateLabel(t,span){return span>45*86400000?new Date(t).toLocaleDateString('en-GB',{month:'long',year:'numeric'}):new Date(t).toLocaleDateString('en-GB')}
  function drawAxes(g,w,h,q,mm,pad,t0,t1){var st=step(mm.hi-mm.lo),start=Math.ceil(mm.lo/st)*st,span=t1-t0;g.font=11*q+'px Courier New';for(var v=start;v<=mm.hi+st*.5;v+=st){var y=pad.top+((mm.hi-v)/(mm.hi-mm.lo))*(h-pad.top-pad.bottom);g.fillStyle='#f5f7fb';g.textAlign='left';g.fillText('£'+fmt(v,0).replace('-0','0'),8*q,y+4*q)}g.save();g.strokeStyle='rgba(255,255,255,.26)';g.lineWidth=1*q;g.beginPath();g.moveTo(pad.left,h-pad.bottom);g.lineTo(w-pad.right,h-pad.bottom);g.stroke();g.fillStyle='#f5f7fb';g.font=11*q+'px Courier New';g.textAlign='left';g.fillText(dateLabel(t0,span),pad.left,h-pad.bottom+24*q);g.textAlign='right';g.fillText(dateLabel(t1,span),w-pad.right,h-pad.bottom+24*q);g.restore();g.textAlign='left'}
  function drawKey(g,q,pad,isFull,result){var items=result.mode==='daily'?[['Average','#00ffff'],['High','#ffcc00'],['Low','#ff3333']]:[['Winter','#00ffff'],['Spring','#00ff88'],['Summer','#ffcc00'],['Autumn','#c79245']];if((result.forecastRows||[]).length)items.push(['Forecast','#8a95a8']);var x=pad.left,y=pad.top-24*q;g.save();g.font=(isFull?8.5:9)*q+'px Courier New';items.forEach(function(it){g.fillStyle=it[1];g.shadowColor=it[1];g.shadowBlur=4*q;g.fillRect(x,y-7*q,8*q,8*q);g.shadowBlur=0;g.fillStyle='#9aa3b6';g.fillText(it[0],x+12*q,y);x+=(isFull?58:66)*q});g.restore()}
  function pence(v){return fmt(Number(v)/10,2)}
  function set(id,v){var e=document.getElementById(id);if(e)e.textContent=v}
  function forecastHealth(result){var f=result.forecastRows||[],a=result.rows||[];if(!f.length||!a.length)return{label:'Forecast health: awaiting actual data',skill:0,mae:null,n:0};var map={};f.forEach(function(r){map[r.date]=forecastValue(r)});var errs=[];a.forEach(function(r){var key=result.mode==='daily'?r.date:(time(r)||'').slice(0,10);var fv=map[key],av=actualValue(r,result.mode);if(fv!=null&&!isNaN(fv)&&!isNaN(av))errs.push(Math.abs(av-fv))});if(errs.length<7)return{label:'Forecast health: awaiting more actual data',skill:0,mae:null,n:errs.length};var mae=errs.reduce(function(x,y){return x+y},0)/errs.length;var label=mae<15?'Tracking close':mae<35?'Moderate deviation':mae<70?'Large deviation':'Market moved beyond seasonal baseline';var skill=Math.max(0,Math.min(1,1-mae/100));return{label:label,skill:skill,mae:mae,n:errs.length}}
  function drawHealthBar(g,result,q,w,h,pad){var health=forecastHealth(result),x=pad.left,y=h-34*q,bw=w-pad.left-pad.right,bh=10*q;g.save();g.fillStyle='rgba(255,255,255,.08)';g.fillRect(x,y,bw,bh);g.fillStyle=health.skill>.65?'#00ff88':health.skill>.3?'#ffcc00':'#ff4444';g.fillRect(x,y,bw*health.skill,bh);g.strokeStyle='rgba(0,255,255,.25)';g.strokeRect(x,y,bw,bh);g.fillStyle='#9aa3b6';g.font=9*q+'px Courier New';g.textAlign='left';var txt=health.label+(health.mae!=null?' · MAE £'+fmt(health.mae,2)+'/MWh · n='+health.n:'');g.fillText(txt,x,y-8*q);g.restore()}
  function compactDateText(t){return String(t||'').replace(/January/g,'Jan').replace(/February/g,'Feb').replace(/March/g,'Mar').replace(/April/g,'Apr').replace(/June/g,'Jun').replace(/July/g,'Jul').replace(/August/g,'Aug').replace(/September/g,'Sep').replace(/October/g,'Oct').replace(/November/g,'Nov').replace(/December/g,'Dec')}
  function drawSummary(g,s,q,w,h,pad,isFull,isLandscape){if(isFull&&isLandscape)return;var cssW=w/q,boxH=(isFull?172:118)*q,x=pad.left,bw=w-pad.left-pad.right,y=isFull?h-boxH-82*q:h-128*q;g.save();g.fillStyle='rgba(5,7,12,.92)';g.strokeStyle='rgba(0,255,255,.55)';g.lineWidth=1.2*q;g.shadowColor='rgba(0,255,255,.24)';g.shadowBlur=10*q;g.beginPath();g.roundRect(x,y,bw,boxH,10*q);g.fill();g.stroke();g.shadowBlur=0;if(isFull){var left=x+18*q,right=x+bw-18*q,labelFont=(cssW<430?10.5:12.2)*q,valueFont=(cssW<430?10.2:12)*q,dateFont=(cssW<430?8.4:9.8)*q;function row(label,val,date,clock,yy){g.font='900 '+labelFont+'px Courier New';g.fillStyle='#ff5555';g.textAlign='left';g.fillText(label,left,yy);g.font='900 '+valueFont+'px Courier New';g.fillStyle='#f5f7fb';g.textAlign='right';g.fillText(pence(val)+'p/kWh   £'+fmt(val,2)+'/MWh',right,yy);g.font='900 '+dateFont+'px Courier New';g.fillStyle='#ff7777';g.textAlign='left';g.fillText(compactDateText(date)+(clock?'  '+clock:''),left,yy+18*q)}row('High',s.hiValue,s.hiDate,s.hiClock,y+34*q);row('Average',s.avg,s.avgDate,'',y+86*q);row('Low',s.loValue,s.loDate,s.loClock,y+138*q)}else{g.fillStyle='#f5f7fb';g.textAlign='center';var cx=x+bw/2;function line(label,val,date,clock){return label+'  '+pence(val)+'p/kWh   £'+fmt(val,2)+'/MWh   '+compactDateText(date)+(clock?' '+clock:'')}g.font='900 '+(cssW<720?8.2:10.5)*q+'px Courier New';g.fillText(line('High',s.hiValue,s.hiDate,s.hiClock),cx,y+24*q);g.fillText(line('Average',s.avg,s.avgDate,''),cx,y+58*q);g.fillText(line('Low',s.loValue,s.loDate,s.loClock),cx,y+92*q)}g.restore()}
  function decimateRows(rows,limit){if(!rows||rows.length<=limit)return rows||[];var out=[],bucket=Math.ceil(rows.length/limit);for(var i=0;i<rows.length;i+=bucket){var slice=rows.slice(i,i+bucket),hi=slice[0],lo=slice[0];slice.forEach(function(r){if(price(r)>price(hi))hi=r;if(price(r)<price(lo))lo=r});if(new Date(time(lo))<new Date(time(hi))){out.push(lo);if(hi!==lo)out.push(hi)}else{out.push(hi);if(hi!==lo)out.push(lo)}}return out.sort(function(a,b){return new Date(time(a))-new Date(time(b))})}
  function drawForecast(g,result,q,X,Y){var rows=result.forecastRows||[];if(rows.length<2)return;g.save();g.lineWidth=1.7*q;g.lineCap='round';g.lineJoin='round';g.setLineDash([7*q,6*q]);g.strokeStyle='rgba(180,190,210,.76)';g.shadowColor='rgba(180,190,210,.35)';g.shadowBlur=4*q;g.beginPath();rows.forEach(function(r,i){var x=X(r,true),y=Y(forecastValue(r));if(i)g.lineTo(x,y);else g.moveTo(x,y)});g.stroke();g.restore()}
  function drawDailyLines(g,result,q,X,Y){var rows=result.rows||[];if(rows.length<2)return;var series=[['high','#ffcc00',2.1],['average','#00ffff',2.4],['low','#ff3333',2.1]];series.forEach(function(s){g.save();g.lineWidth=s[2]*q;g.lineCap='round';g.lineJoin='round';g.setLineDash([]);g.strokeStyle=s[1];g.shadowColor=s[1];g.shadowBlur=5*q;g.beginPath();var started=false;rows.forEach(function(r){var v=Number(r[s[0]]);if(isNaN(v))return;var x=X(r),y=Y(v);if(started)g.lineTo(x,y);else{g.moveTo(x,y);started=true}});g.stroke();g.restore()})}
  function renderTo(canvasId,result){var c=document.getElementById(canvasId);if(!c)return;var isFull=canvasId==='price-history-fullscreen-canvas';var q=window.devicePixelRatio||1,r=c.getBoundingClientRect();c.width=Math.max(320,Math.floor((r.width||1200)*q));c.height=Math.max(360,Math.floor((r.height||720)*q));var g=c.getContext('2d'),w=c.width,h=c.height,cssW=w/q,cssH=h/q,isLandscape=isFull&&cssW>cssH;var pad=isFull?(isLandscape?{left:50*q,right:22*q,top:74*q,bottom:44*q}:{left:58*q,right:18*q,top:104*q,bottom:285*q}):{left:74*q,right:24*q,top:96*q,bottom:284*q};g.clearRect(0,0,w,h);g.fillStyle='#05070c';g.fillRect(0,0,w,h);var vals=values(result);if(vals.length<2)vals=[0,100];var mm=minMax(vals),t0=result.start.getTime(),t1=result.end.getTime();drawAxes(g,w,h,q,mm,pad,t0,t1);drawKey(g,q,pad,isFull,result);function X(row,isForecast){var t;if(result.mode==='daily'||isForecast)t=new Date(row.date+'T12:00:00Z').getTime();else t=new Date(time(row)).getTime();return pad.left+((t-t0)/(t1-t0))*(w-pad.left-pad.right)}function Y(v){return pad.top+((mm.hi-v)/(mm.hi-mm.lo))*(h-pad.top-pad.bottom)}drawForecast(g,result,q,X,Y);if(result.mode==='daily'){drawDailyLines(g,result,q,X,Y)}else{var lineRows=decimateRows(result.rows,Math.max(900,Math.floor((w/q)*1.8)));g.save();g.lineWidth=(isLandscape?2.4:2.1)*q;g.lineCap='round';g.lineJoin='round';for(var j=1;j<lineRows.length;j++){var aa=lineRows[j-1],bb=lineRows[j],col2=seasonColor(time(bb));g.strokeStyle=col2;g.shadowColor=col2;g.shadowBlur=(isLandscape?7:5)*q;g.beginPath();g.moveTo(X(aa),Y(price(aa)));g.lineTo(X(bb),Y(price(bb)));g.stroke()}g.restore()}var s=stats(result);if(s){var hx=X(s.hi),hy=Y(s.hiValue),lx=X(s.lo),ly=Y(s.loValue);g.save();g.fillStyle='#ff3333';g.shadowColor='rgba(0,255,255,.8)';g.shadowBlur=8*q;g.beginPath();g.arc(hx,hy,4.5*q,0,Math.PI*2);g.fill();g.beginPath();g.arc(lx,ly,4.5*q,0,Math.PI*2);g.fill();g.restore();drawSummary(g,s,q,w,h,pad,isFull,isLandscape);set('ph-latest-price','£'+fmt(s.avg,2)+'/MWh');set('ph-latest-time',s.avgDate);set('ph-row-count',(result.rows||[]).length.toLocaleString('en-GB'));set('ph-source','Elexon BMRS')}else{g.save();g.fillStyle='#00ffff';g.font='900 '+13*q+'px Courier New';g.textAlign='center';g.fillText('No actual data yet · showing indicative seasonal baseline',w/2,pad.top+48*q);g.restore();set('ph-latest-price','Forecast baseline');set('ph-row-count','0');set('ph-source','Seasonal baseline')}if(!isFull&&result.forecastRows&&result.forecastRows.length)drawHealthBar(g,result,q,w,h,pad);set('price-history-range-status',new Date(result.start).toLocaleDateString('en-GB')+' to '+new Date(result.end).toLocaleDateString('en-GB')+' | '+(result.rows||[]).length.toLocaleString('en-GB')+' actual points')}
  function render(result){lastResult=result;renderTo('price-history-canvas',result);var o=document.getElementById('price-history-fullscreen-overlay');if(o&&o.classList.contains('open'))renderTo('price-history-fullscreen-canvas',result)}
  function redrawFullscreen(){if(lastResult)renderTo('price-history-fullscreen-canvas',lastResult)}
  return{render:render,redrawFullscreen:redrawFullscreen};
})();