window.V6RenderPriceChart=(function(){
  function fmt(n,d){return n==null||isNaN(Number(n))?'—':Number(n).toLocaleString('en-GB',{minimumFractionDigits:d,maximumFractionDigits:d})}
  function seasonColor(t){var m=new Date(t).getUTCMonth()+1;if(m===12||m<=2)return'#00ffff';if(m>=3&&m<=5)return'#00ff88';if(m>=6&&m<=8)return'#ffcc00';return'#c79245'}
  function values(result){if(result.mode==='daily')return result.rows.flatMap(function(r){return [r.high,r.low,r.average].filter(function(v){return v!=null&&!isNaN(Number(v))}).map(Number)});return result.rows.map(function(r){return Number(r.price)})}
  function stats(result){var rows=result.rows;if(!rows.length)return null;if(result.mode==='daily'){var hi=rows[0],lo=rows[0],sum=0,c=0;rows.forEach(function(r){if(r.average!=null){sum+=Number(r.average);c++}if(Number(r.high)>Number(hi.high))hi=r;if(Number(r.low)<Number(lo.low))lo=r});return{hi:hi,lo:lo,avg:c?sum/c:null,hiValue:Number(hi.high),loValue:Number(lo.low),hiTime:hi.date+' '+(hi.highAt||''),loTime:lo.date+' '+(lo.lowAt||'')}}var h=rows[0],l=rows[0],s=0;rows.forEach(function(r){s+=Number(r.price);if(Number(r.price)>Number(h.price))h=r;if(Number(r.price)<Number(l.price))l=r});return{hi:h,lo:l,avg:s/rows.length,hiValue:Number(h.price),loValue:Number(l.price),hiTime:new Date(h.time).toLocaleString('en-GB'),loTime:new Date(l.time).toLocaleString('en-GB')}}
  function minMax(v){var lo=0,hi=0;v.forEach(function(x){if(x<lo)lo=x;if(x>hi)hi=x});if(lo===hi)hi=lo+1;var m=(hi-lo)*.06;return{lo:lo-m,hi:hi+m}}
  function step(span){var raw=span/10,p=Math.pow(10,Math.floor(Math.log10(Math.max(raw,1)))),n=raw/p;if(n<=1)return p;if(n<=2)return 2*p;if(n<=5)return 5*p;return 10*p}
  function drawAxes(g,w,h,q,mm,pad){var st=step(mm.hi-mm.lo),start=Math.ceil(mm.lo/st)*st;g.font=11*q+'px Courier New';for(var v=start;v<=mm.hi+st*.5;v+=st){var y=pad.top+((mm.hi-v)/(mm.hi-mm.lo))*(h-pad.top-pad.bottom);g.strokeStyle='rgba(255,255,255,.16)';g.beginPath();g.moveTo(pad.left,y);g.lineTo(w-pad.right,y);g.stroke();g.fillStyle='#f5f7fb';g.fillText('£'+fmt(v,0),8*q,y+4*q)}}
  function drawBox(g,q,x,y,align,lines){var pad=8*q,lh=18*q,w=0;g.save();g.font='900 '+14*q+'px Courier New';lines.forEach(function(t){w=Math.max(w,g.measureText(t).width)});var xx=align==='right'?x-w-pad*2:x;g.fillStyle='rgba(5,7,12,.78)';g.strokeStyle='rgba(0,255,255,.35)';g.beginPath();g.roundRect(xx,y-lines.length*lh-pad,w+pad*2,lines.length*lh+pad*2,6*q);g.fill();g.stroke();g.fillStyle='#ff3333';g.textAlign=align;lines.forEach(function(t,i){g.fillText(t,x,y-(lines.length-1-i)*lh)});g.restore()}
  function pence(v){return fmt(Number(v)/10,2)}
  function render(result){var c=document.getElementById('price-history-canvas');if(!c)return;var q=window.devicePixelRatio||1,r=c.getBoundingClientRect();c.width=Math.max(320,Math.floor((r.width||1200)*q));c.height=Math.max(360,Math.floor((r.height||720)*q));var g=c.getContext('2d'),w=c.width,h=c.height,pad={left:74*q,right:24*q,top:82*q,bottom:150*q};g.fillStyle='#05070c';g.fillRect(0,0,w,h);if(!result||!result.rows||result.rows.length<2){g.fillStyle='#00ffff';g.font=14*q+'px Courier New';g.fillText('No data for selected range.',pad.left,42*q);return}var vals=values(result),mm=minMax(vals),t0=result.start.getTime(),t1=result.end.getTime();drawAxes(g,w,h,q,mm,pad);function X(row){var t=result.mode==='daily'?new Date(row.date+'T12:00:00Z').getTime():new Date(row.time).getTime();return pad.left+((t-t0)/(t1-t0))*(w-pad.left-pad.right)}function Y(v){return pad.top+((mm.hi-v)/(mm.hi-mm.lo))*(h-pad.top-pad.bottom)}
    if(result.mode==='daily'){['average','high','low'].forEach(function(k){g.save();g.lineWidth=(k==='average'?2.4:1.6)*q;g.setLineDash(k==='average'?[]:[5*q,4*q]);for(var i=1;i<result.rows.length;i++){var a=result.rows[i-1],b=result.rows[i];if(a[k]==null||b[k]==null)continue;var col=seasonColor(b.date+'T12:00:00Z');g.strokeStyle=col;g.shadowColor=col;g.shadowBlur=4*q;g.beginPath();g.moveTo(X(a),Y(Number(a[k])));g.lineTo(X(b),Y(Number(b[k])));g.stroke()}g.restore()})}else{g.save();g.lineWidth=2.1*q;for(var j=1;j<result.rows.length;j++){var aa=result.rows[j-1],bb=result.rows[j],col2=seasonColor(bb.time);g.strokeStyle=col2;g.shadowColor=col2;g.shadowBlur=4*q;g.beginPath();g.moveTo(X(aa),Y(aa.price));g.lineTo(X(bb),Y(bb.price));g.stroke()}g.restore()}
    var s=stats(result);if(s){var hx=X(s.hi),hy=Y(s.hiValue),lx=X(s.lo),ly=Y(s.loValue);g.fillStyle='#ff3333';g.shadowColor='rgba(0,255,255,.8)';g.shadowBlur=8*q;g.beginPath();g.arc(hx,hy,5*q,0,Math.PI*2);g.fill();g.beginPath();g.arc(lx,ly,5*q,0,Math.PI*2);g.fill();drawBox(g,q,hx<w/2?hx+18*q:hx-18*q,Math.max(pad.top+54*q,hy-24*q),hx<w/2?'left':'right',['HIGH','£'+fmt(s.hiValue,2)+'/MWh',s.hiTime]);drawBox(g,q,lx<w/2?lx+18*q:lx-18*q,Math.min(h-pad.bottom-28*q,ly+54*q),lx<w/2?'left':'right',['LOW','£'+fmt(s.loValue,2)+'/MWh',s.loTime]);g.shadowBlur=0;g.fillStyle='rgba(5,7,12,.72)';g.strokeStyle='rgba(0,255,255,.26)';g.beginPath();g.roundRect(pad.left,h-66*q,w-pad.left-pad.right,42*q,6*q);g.fill();g.stroke();g.fillStyle='#f5f7fb';g.font='900 '+10*q+'px Courier New';g.textAlign='center';g.fillText('HIGH '+pence(s.hiValue)+'p/kWh (£'+fmt(s.hiValue,2)+'/MWh)  AVG '+pence(s.avg)+'p/kWh (£'+fmt(s.avg,2)+'/MWh)  LOW '+pence(s.loValue)+'p/kWh (£'+fmt(s.loValue,2)+'/MWh)',w/2,h-43*q)}
  }
  return{render:render};
})();
