window.V6RenderPriceChart=(function(){
  var lastResult=null;
  function fmt(n,d){return n==null||isNaN(Number(n))?'—':Number(n).toLocaleString('en-GB',{minimumFractionDigits:d,maximumFractionDigits:d})}
  function price(r){return Number(r.price!=null?r.price:r.priceGBPperMWh)}
  function time(r){return r.time||r.priceTimeUTC||r.date}
  function pence(v){return fmt(Number(v)/10,2)}
  function set(id,v){var e=document.getElementById(id);if(e)e.textContent=v}
  function niceDate(v){var d=v instanceof Date?v:new Date(String(v||'').replace(' ','T')+'Z');if(isNaN(d.getTime()))d=new Date(v);return isNaN(d.getTime())?'—':d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}
  function niceClock(v){var m=String(v||'').match(/(\d{2}:\d{2})/);return m?m[1]:''}
  function seasonName(t){var m=new Date(t).getUTCMonth()+1;if(m===12||m<=2)return'Winter';if(m>=3&&m<=5)return'Spring';if(m>=6&&m<=8)return'Summer';return'Autumn'}
  function seasonColor(t){var s=seasonName(t);if(s==='Winter')return'#00ffff';if(s==='Spring')return'#00ff88';if(s==='Summer')return'#ffcc00';return'#c79245'}
  function actualValue(r,mode){return mode==='daily'?Number(r.average):price(r)}
  function forecastValue(r){return Number(r.forecast!=null?r.forecast:r.average)}
  function values(result){var out=[];(result.rows||[]).forEach(function(r){if(result.mode==='daily'){['average','high','low'].forEach(function(k){var v=Number(r[k]);if(!isNaN(v))out.push(v)})}else{var v=price(r);if(!isNaN(v))out.push(v)}});(result.forecastRows||[]).forEach(function(r){var f=forecastValue(r);if(!isNaN(f))out.push(f)});return out}
  function stats(result){var rows=result.rows||[];if(!rows.length)return null;if(result.mode==='daily'){var valid=rows.filter(function(r){return r.average!=null&&r.high!=null&&r.low!=null&&!isNaN(Number(r.average))&&!isNaN(Number(r.high))&&!isNaN(Number(r.low))});if(!valid.length)return null;var hi=valid[0],lo=valid[0],sum=0;valid.forEach(function(r){sum+=Number(r.average);if(Number(r.high)>Number(hi.high))hi=r;if(Number(r.low)<Number(lo.low))lo=r});return{hi:hi,lo:lo,avg:sum/valid.length,hiValue:Number(hi.high),loValue:Number(lo.low),hiDate:niceDate(hi.date),loDate:niceDate(lo.date),hiClock:hi.highAt||'',loClock:lo.lowAt||'',avgDate:'Visible period'}}var h=rows[0],l=rows[0],s=0;rows.forEach(function(r){var v=price(r);s+=v;if(v>price(h))h=r;if(v<price(l))l=r});return{hi:h,lo:l,avg:s/rows.length,hiValue:price(h),loValue:price(l),hiDate:niceDate(time(h)),loDate:niceDate(time(l)),hiClock:niceClock(time(h)),loClock:niceClock(time(l)),avgDate:'Visible period'}}
  function minMax(v){var lo=0,hi=0;v.forEach(function(x){if(x<lo)lo=x;if(x>hi)hi=x});if(lo===hi)hi=lo+1;var m=Math.max((hi-lo)*.10,10);return{lo:lo-m,hi:hi+m}}
  function step(span){var raw=span/5,p=Math.pow(10,Math.floor(Math.log10(Math.max(raw,1)))),n=raw/p;if(n<=1)return p;if(n<=2)return 2*p;if(n<=5)return 5*p;return 10*p}
  function dateLabel(t,span){return span>45*86400000?new Date(t).toLocaleDateString('en-GB',{month:'short',year:'numeric'}):new Date(t).toLocaleDateString('en-GB')}
  function drawAxes(g,w,h,q,mm,pad,t0,t1){var st=step(mm.hi-mm.lo),start=Math.ceil(mm.lo/st)*st,span=t1-t0;g.save();g.font=11*q+'px Courier New';for(var v=start;v<=mm.hi+st*.5;v+=st){var y=pad.top+((mm.hi-v)/(mm.hi-mm.lo))*(h-pad.top-pad.bottom);g.fillStyle='#f5f7fb';g.textAlign='left';g.fillText('£'+fmt(v,0).replace('-0','0'),8*q,y+4*q)}g.strokeStyle='rgba(255,255,255,.25)';g.lineWidth=1*q;g.beginPath();g.moveTo(pad.left,h-pad.bottom);g.lineTo(w-pad.right,h-pad.bottom);g.stroke();g.fillStyle='#f5f7fb';g.font=11*q+'px Courier New';g.textAlign='left';g.fillText(dateLabel(t0,span),pad.left,h-pad.bottom+25*q);g.textAlign='right';g.fillText(dateLabel(t1,span),w-pad.right,h-pad.bottom+25*q);g.restore()}
  function drawKey(g,q,pad,isFull,result){var items=result.mode==='daily'?[['Average','#00ffff'],['High','#ffcc00'],['Low','#ff3333']]:[['Winter','#00ffff'],['Spring','#00ff88'],['Summer','#ffcc00'],['Autumn','#c79245']];var x=pad.left,y=pad.top-26*q;g.save();g.font=(isFull?8.5:9.5)*q+'px Courier New';items.forEach(function(it){g.fillStyle=it[1];g.shadowColor=it[1];g.shadowBlur=5*q;g.fillRect(x,y-7*q,8*q,8*q);g.shadowBlur=0;g.fillStyle='#9aa3b6';g.fillText(it[0],x+13*q,y);x+=(isFull?58:72)*q});g.restore()}
  function decimateRows(rows,limit){if(!rows||rows.length<=limit)return rows||[];var out=[],bucket=Math.ceil(rows.length/limit);for(var i=0;i<rows.length;i+=bucket){var slice=rows.slice(i,i+bucket),hi=slice[0],lo=slice[0];slice.forEach(function(r){if(price(r)>price(hi))hi=r;if(price(r)<price(lo))lo=r});out.push(hi);if(lo!==hi)out.push(lo)}return out.sort(function(a,b){return new Date(time(a))-new Date(time(b))})}
  function drawDot(g,x,y,q,label){g.save();g.fillStyle='#ff3333';g.shadowColor='rgba(0,255,255,.85)';g.shadowBlur=8*q;g.beginPath();g.arc(x,y,5.2*q,0,Math.PI*2);g.fill();g.restore()}
  function boxText(label,val,date,clock){return[label,'£'+fmt(val,2)+'/MWh   '+pence(val)+'p/kWh',date+(clock?' '+clock:'')]}
  function drawBox(g,lines,q,cx,cy,maxW){var pad=8*q,lh=16*q,wid=0;g.save();g.font='900 '+9.5*q+'px Courier New';lines.forEach(function(t){wid=Math.max(wid,g.measureText(t).width)});var bw=Math.min(wid+pad*2,maxW||320*q),bh=lines.length*lh+pad*2,xx=cx-bw/2,yy=cy-bh/2;if(xx<8*q)xx=8*q;if(xx+bw>g.canvas.width-8*q)xx=g.canvas.width-bw-8*q;if(yy<8*q)yy=8*q;if(yy+bh>g.canvas.height-8*q)yy=g.canvas.height-bh-8*q;g.fillStyle='rgba(5,7,12,.86)';g.strokeStyle='rgba(0,255,255,.55)';g.lineWidth=1*q;g.shadowColor='rgba(0,255,255,.26)';g.shadowBlur=8*q;g.beginPath();g.roundRect(xx,yy,bw,bh,7*q);g.fill();g.stroke();g.shadowBlur=0;g.textAlign='left';lines.forEach(function(t,i){var s=String(t);g.fillStyle=i===0?'#ff3333':(i===1?'#f5f7fb':'#9aa3b6');while(s.length>5&&g.measureText(s).width>bw-pad*2){s=s.slice(0,-1)}g.fillText(s,xx+pad,yy+pad+lh*(i+.78))});g.restore()}
  function drawTrackers(g,s,q,w,h,pad,X,Y){var top=pad.top,bottom=h-pad.bottom,plotH=bottom-top,zoneX=(pad.left+w-pad.right)/2;var hiX=X(s.hi),hiY=Y(s.hiValue),loX=X(s.lo),loY=Y(s.loValue),avgY=Y(s.avg);drawDot(g,hiX,hiY,q);drawDot(g,loX,loY,q);drawBox(g,boxText('HIGH',s.hiValue,s.hiDate,s.hiClock),q,zoneX,top+plotH*.18,w-pad.left-pad.right);drawBox(g,boxText('AVERAGE',s.avg,'Visible period',''),q,zoneX,top+plotH*.50,w-pad.left-pad.right);drawBox(g,boxText('LOW',s.loValue,s.loDate,s.loClock),q,zoneX,top+plotH*.82,w-pad.left-pad.right)}
  function drawDaily(g,result,q,X,Y){var rows=result.rows||[];[['high','#ffcc00'],['average','#00ffff'],['low','#ff3333']].forEach(function(s){g.save();g.lineWidth=2.2*q;g.lineCap='round';g.lineJoin='round';g.strokeStyle=s[1];g.shadowColor=s[1];g.shadowBlur=5*q;g.beginPath();var on=false;rows.forEach(function(r){var v=Number(r[s[0]]);if(isNaN(v))return;var x=X(r),y=Y(v);if(on)g.lineTo(x,y);else{g.moveTo(x,y);on=true}});g.stroke();g.restore()})}
  function renderTo(canvasId,result){var c=document.getElementById(canvasId);if(!c)return;var isFull=canvasId==='price-history-fullscreen-canvas';var q=window.devicePixelRatio||1,r=c.getBoundingClientRect();c.width=Math.max(320,Math.floor((r.width||900)*q));c.height=Math.max(420,Math.floor((r.height||720)*q));var g=c.getContext('2d'),w=c.width,h=c.height,cssW=w/q,cssH=h/q,isLandscape=isFull&&cssW>cssH;var pad=isFull?(isLandscape?{left:50*q,right:24*q,top:82*q,bottom:54*q}:{left:58*q,right:18*q,top:132*q,bottom:92*q}):{left:74*q,right:24*q,top:96*q,bottom:96*q};g.clearRect(0,0,w,h);g.fillStyle='#05070c';g.fillRect(0,0,w,h);var vals=values(result);if(vals.length<2)vals=[0,100];var mm=minMax(vals),t0=result.start.getTime(),t1=result.end.getTime();drawAxes(g,w,h,q,mm,pad,t0,t1);drawKey(g,q,pad,isFull,result);function X(row){var t=result.mode==='daily'?new Date(row.date+'T12:00:00Z').getTime():new Date(time(row)).getTime();return pad.left+((t-t0)/(t1-t0))*(w-pad.left-pad.right)}function Y(v){return pad.top+((mm.hi-v)/(mm.hi-mm.lo))*(h-pad.top-pad.bottom)}if(result.mode==='daily'){drawDaily(g,result,q,X,Y)}else{var rows=decimateRows(result.rows,Math.max(900,Math.floor((w/q)*1.8)));g.save();g.lineWidth=(isLandscape?2.4:2.1)*q;g.lineCap='round';g.lineJoin='round';for(var j=1;j<rows.length;j++){var a=rows[j-1],b=rows[j],col=seasonColor(time(b));g.strokeStyle=col;g.shadowColor=col;g.shadowBlur=5*q;g.beginPath();g.moveTo(X(a),Y(price(a)));g.lineTo(X(b),Y(price(b)));g.stroke()}g.restore()}var s=stats(result);if(s){drawTrackers(g,s,q,w,h,pad,X,Y);set('ph-latest-price','£'+fmt(s.avg,2)+'/MWh');set('ph-high-price','£'+fmt(s.hiValue,2));set('ph-low-price','£'+fmt(s.loValue,2));set('ph-avg-price','£'+fmt(s.avg,2))}}
  function render(canvasId,result){lastResult=result;renderTo(canvasId,result);renderTo('price-history-fullscreen-canvas',result)}
  function redrawFullscreen(){if(lastResult)renderTo('price-history-fullscreen-canvas',lastResult)}
  return{render:render,redrawFullscreen:redrawFullscreen};
})();
