(function(){
  if(!window.V6RenderPriceChart||window.V6RenderPriceChart.__boxOverlayApplied)return;
  var original=window.V6RenderPriceChart.render;
  function fmt(n,d){return n==null||isNaN(Number(n))?'—':Number(n).toLocaleString('en-GB',{minimumFractionDigits:d,maximumFractionDigits:d})}
  function price(r){return Number(r.price!=null?r.price:r.priceGBPperMWh)}
  function time(r){return r.time||r.priceTimeUTC||r.date}
  function niceDate(v){var d=v instanceof Date?v:new Date(String(v||'').replace(' ','T')+'Z');if(isNaN(d.getTime()))d=new Date(v);return isNaN(d.getTime())?'—':d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}
  function niceClock(v){var m=String(v||'').match(/(\d{2}:\d{2})/);return m?m[1]:''}
  function pence(v){return fmt(Number(v)/10,2)}
  function compactDateText(t){return String(t||'').replace(/January/g,'Jan').replace(/February/g,'Feb').replace(/March/g,'Mar').replace(/April/g,'Apr').replace(/June/g,'Jun').replace(/July/g,'Jul').replace(/August/g,'Aug').replace(/September/g,'Sep').replace(/October/g,'Oct').replace(/November/g,'Nov').replace(/December/g,'Dec')}
  function stats(result){var rows=result.rows||[];if(!rows.length)return null;if(result.mode==='daily'){var valid=rows.filter(function(r){return r.average!=null&&r.high!=null&&r.low!=null&&!isNaN(Number(r.average))&&!isNaN(Number(r.high))&&!isNaN(Number(r.low))});if(!valid.length)return null;var hi=valid[0],lo=valid[0],sum=0;valid.forEach(function(r){sum+=Number(r.average);if(Number(r.high)>Number(hi.high))hi=r;if(Number(r.low)<Number(lo.low))lo=r});return{hi:hi,lo:lo,avg:sum/valid.length,hiValue:Number(hi.high),loValue:Number(lo.low),hiDate:niceDate(hi.date),loDate:niceDate(lo.date),hiClock:hi.highAt||'',loClock:lo.lowAt||''}}var h=rows[0],l=rows[0],s=0;rows.forEach(function(r){var v=price(r);s+=v;if(v>price(h))h=r;if(v<price(l))l=r});return{hi:h,lo:l,avg:s/rows.length,hiValue:price(h),loValue:price(l),hiDate:niceDate(time(h)),loDate:niceDate(time(l)),hiClock:niceClock(time(h)),loClock:niceClock(time(l))}}
  function values(result){var out=[];(result.rows||[]).forEach(function(r){if(result.mode==='daily'){['average','high','low'].forEach(function(k){var v=Number(r[k]);if(!isNaN(v))out.push(v)})}else{var v=price(r);if(!isNaN(v))out.push(v)}});return out.length?out:[0,100]}
  function minMax(v){var lo=0,hi=0;v.forEach(function(x){if(x<lo)lo=x;if(x>hi)hi=x});if(lo===hi)hi=lo+1;var m=Math.max((hi-lo)*.08,10);return{lo:lo-m,hi:hi+m}}
  function boxText(label,val,date,clock){return[label,'£'+fmt(val,2)+'/MWh   '+pence(val)+'p/kWh',compactDateText(date)+(clock?' '+clock:'')]}
  function boxSize(g,lines,q){var pad=7*q,lh=15*q,w=0;g.font='900 '+9.5*q+'px Courier New';lines.forEach(function(t){w=Math.max(w,g.measureText(t).width)});return{w:w+pad*2,h:lines.length*lh+pad*2,pad:pad,lh:lh}}
  function drawBox(g,lines,q,cx,cy,maxW){var s=boxSize(g,lines,q),bw=Math.min(s.w,maxW||s.w),bh=s.h,xx=cx-bw/2,yy=cy-bh/2;if(xx<8*q)xx=8*q;if(xx+bw>g.canvas.width-8*q)xx=g.canvas.width-bw-8*q;if(yy<8*q)yy=8*q;if(yy+bh>g.canvas.height-8*q)yy=g.canvas.height-bh-8*q;g.save();g.fillStyle='rgba(5,7,12,.92)';g.strokeStyle='rgba(0,255,255,.62)';g.lineWidth=1.2*q;g.shadowColor='rgba(0,255,255,.30)';g.shadowBlur=9*q;g.beginPath();g.roundRect(xx,yy,bw,bh,7*q);g.fill();g.stroke();g.shadowBlur=0;g.textAlign='left';g.font='900 '+9.5*q+'px Courier New';lines.forEach(function(t,i){var str=String(t);g.fillStyle=i===0?'#ff3333':(i===1?'#f5f7fb':'#9aa3b6');while(str.length>5&&g.measureText(str).width>bw-s.pad*2){str=str.slice(0,-1)}g.fillText(str,xx+s.pad,yy+s.pad+s.lh*(i+.78))});g.restore();return{x:xx,y:yy,w:bw,h:bh}}
  function coverBox(g,x,y,w,h,q){g.save();g.fillStyle='#05070c';g.fillRect(x-4*q,y-4*q,w+8*q,h+8*q);g.restore()}
  function overlay(canvasId,result){var c=document.getElementById(canvasId);if(!c||!result)return;var q=window.devicePixelRatio||1,g=c.getContext('2d'),w=c.width,h=c.height,cssW=w/q,cssH=h/q,isFull=canvasId==='price-history-fullscreen-canvas',isLandscape=isFull&&cssW>cssH;if(isLandscape)return;var pad=isFull?{left:58*q,right:18*q,top:104*q,bottom:285*q}:{left:74*q,right:24*q,top:96*q,bottom:284*q};var mm=minMax(values(result)),t0=result.start.getTime(),t1=result.end.getTime();function X(row){var t=result.mode==='daily'?new Date(row.date+'T12:00:00Z').getTime():new Date(time(row)).getTime();return pad.left+((t-t0)/(t1-t0))*(w-pad.left-pad.right)}function Y(v){return pad.top+((mm.hi-v)/(mm.hi-mm.lo))*(h-pad.top-pad.bottom)}var s=stats(result);if(!s)return;var hiX=X(s.hi),hiY=Y(s.hiValue),loX=X(s.lo),loY=Y(s.loValue),avgX=(pad.left+w-pad.right)/2,avgY=Y(s.avg);
    g.save();g.strokeStyle='#05070c';g.lineWidth=7*q;g.lineCap='round';g.beginPath();g.moveTo(hiX,hiY);g.lineTo(Math.min(w-pad.right-150*q,hiX+22*q),Math.max(pad.top+70*q,Math.min(h-pad.bottom-18*q,hiY+70*q))-22*q);g.moveTo(avgX,avgY);g.lineTo(avgX,Math.max(pad.top+118*q,Math.min(h-pad.bottom-74*q,avgY-42*q))-22*q);g.moveTo(loX,loY);g.lineTo(Math.max(pad.left+150*q,loX-22*q),Math.max(pad.top+74*q,Math.min(h-pad.bottom-28*q,loY-46*q))-22*q);g.stroke();g.restore();
    var oldHigh=boxSize(g,boxText('HIGH',s.hiValue,s.hiDate,s.hiClock),q),oldAvg=boxSize(g,boxText('AVERAGE',s.avg,'Visible period',''),q),oldLow=boxSize(g,boxText('LOW',s.loValue,s.loDate,s.loClock),q);coverBox(g,Math.min(w-pad.right-150*q,hiX+22*q),Math.max(pad.top+70*q,Math.min(h-pad.bottom-18*q,hiY+70*q))-oldHigh.h+4*q,oldHigh.w,oldHigh.h,q);coverBox(g,avgX-oldAvg.w/2,Math.max(pad.top+118*q,Math.min(h-pad.bottom-74*q,avgY-42*q))-oldAvg.h+4*q,oldAvg.w,oldAvg.h,q);coverBox(g,Math.max(pad.left+150*q,loX-22*q)-oldLow.w,Math.max(pad.top+74*q,Math.min(h-pad.bottom-28*q,loY-46*q))-oldLow.h+4*q,oldLow.w,oldLow.h,q);
    var blankTop=h-pad.bottom+58*q,available=Math.max(150*q,h-blankTop-18*q),rowGap=available/3,boxX=(pad.left+w-pad.right)/2,maxW=w-pad.left-pad.right;var targets=[{x:hiX,y:hiY,cx:boxX,cy:blankTop+rowGap*.35,lines:boxText('HIGH',s.hiValue,s.hiDate,s.hiClock)},{x:avgX,y:avgY,cx:boxX,cy:blankTop+rowGap*1.35,lines:boxText('AVERAGE',s.avg,'Visible period','')},{x:loX,y:loY,cx:boxX,cy:blankTop+rowGap*2.35,lines:boxText('LOW',s.loValue,s.loDate,s.loClock)}];targets.forEach(function(it){g.save();g.strokeStyle='rgba(255,51,51,.82)';g.shadowColor='rgba(0,255,255,.45)';g.shadowBlur=7*q;g.lineWidth=1.2*q;g.beginPath();g.moveTo(it.x,it.y);g.lineTo(it.cx,it.cy-28*q);g.stroke();g.restore();drawBox(g,it.lines,q,it.cx,it.cy,maxW)});
  }
  window.V6RenderPriceChart.render=function(canvasId,result){original.call(window.V6RenderPriceChart,canvasId,result);overlay(canvasId,result);overlay('price-history-fullscreen-canvas',result)};
  window.V6RenderPriceChart.__boxOverlayApplied=true;
})();
