window.V6RenderForecastChart=(function(){
  var last=null,showAnnotations=false;
  function fmt(n,d){return n==null||isNaN(Number(n))?'—':Number(n).toLocaleString('en-GB',{minimumFractionDigits:d,maximumFractionDigits:d})}
  function niceDate(v){var d=v instanceof Date?v:new Date(String(v)+'T12:00:00Z');return isNaN(d.getTime())?'—':d.toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}
  function pence(v){return fmt(Number(v)/10,2)}
  function values(rows){var out=[];(rows||[]).forEach(function(r){['forecastHigh','forecastAverage','forecastLow','actualHigh','actualAverage','actualLow'].forEach(function(k){var v=Number(r[k]);if(!isNaN(v))out.push(v)})});return out}
  function minMax(v){var lo=0,hi=0;v.forEach(function(x){if(x<lo)lo=x;if(x>hi)hi=x});if(lo===hi)hi=lo+1;var m=Math.max((hi-lo)*.12,10);return{lo:lo-m,hi:hi+m}}
  function step(span){var raw=span/6,p=Math.pow(10,Math.floor(Math.log10(Math.max(raw,1)))),n=raw/p;if(n<=1)return p;if(n<=2)return 2*p;if(n<=5)return 5*p;return 10*p}
  function xFor(row,t0,t1,w,pad){var t=new Date(row.date+'T12:00:00Z').getTime();return pad.left+((t-t0)/(t1-t0))*(w-pad.left-pad.right)}
  function drawBox(g,q,x,y,align,title,value,date){var lines=[title,'£'+fmt(value,2)+'/MWh',date],pad=8*q,lh=17*q,w=0;g.save();g.font='900 '+12*q+'px Courier New';lines.forEach(function(t){w=Math.max(w,g.measureText(t).width)});var xx=align==='right'?x-w-pad*2:x;g.fillStyle='rgba(5,7,12,.78)';g.strokeStyle='rgba(0,255,255,.28)';g.shadowColor='rgba(0,255,255,.20)';g.shadowBlur=7*q;g.beginPath();g.roundRect(xx,y-lines.length*lh-pad,w+pad*2,lines.length*lh+pad*2,6*q);g.fill();g.stroke();g.shadowBlur=0;g.fillStyle='#ff3333';g.textAlign=align;lines.forEach(function(t,i){g.fillText(t,x,y-(lines.length-1-i)*lh)});g.restore()}
  function render(result){last=result;var c=document.getElementById('price-history-forecast-canvas');if(!c||!result)return;var q=window.devicePixelRatio||1,r=c.getBoundingClientRect();c.width=Math.max(320,Math.floor((r.width||900)*q));c.height=Math.max(440,Math.floor((r.height||620)*q));var g=c.getContext('2d'),w=c.width,h=c.height,pad={left:74*q,right:24*q,top:112*q,bottom:138*q};g.clearRect(0,0,w,h);g.fillStyle='#05070c';g.fillRect(0,0,w,h);
    g.fillStyle='#00ffff';g.font='900 '+14*q+'px Courier New';g.textAlign='left';g.fillText('FORECAST LAYER £/MWh · NEXT 7 DAYS',pad.left,34*q);g.fillStyle='#9aa3b6';g.font=10*q+'px Courier New';g.fillText('Separate from raw published data · dashed forecast, solid dots if actual daily data exists',pad.left,56*q);
    var rows=result.rows||[],mm=minMax(values(rows)),t0=result.start.getTime(),t1=result.end.getTime();var st=step(mm.hi-mm.lo),start=Math.ceil(mm.lo/st)*st;g.font=11*q+'px Courier New';for(var v=start;v<=mm.hi+st*.5;v+=st){var y=pad.top+((mm.hi-v)/(mm.hi-mm.lo))*(h-pad.top-pad.bottom);g.fillStyle='#f5f7fb';g.textAlign='left';g.fillText('£'+fmt(v,0).replace('-0','0'),8*q,y+4*q)}
    g.strokeStyle='rgba(255,255,255,.26)';g.lineWidth=1*q;g.beginPath();g.moveTo(pad.left,h-pad.bottom);g.lineTo(w-pad.right,h-pad.bottom);g.stroke();g.fillStyle='#f5f7fb';g.textAlign='left';g.fillText(niceDate(result.start),pad.left,h-pad.bottom+24*q);g.textAlign='right';g.fillText(niceDate(result.end),w-pad.right,h-pad.bottom+24*q);
    var key=[['High forecast','#ffcc00'],['Average forecast','#00ffff'],['Low forecast','#ff3333']];var kx=pad.left,ky=86*q;g.font=9*q+'px Courier New';key.forEach(function(it){g.fillStyle=it[1];g.shadowColor=it[1];g.shadowBlur=5*q;g.fillRect(kx,ky-7*q,8*q,8*q);g.shadowBlur=0;g.fillStyle='#9aa3b6';g.fillText(it[0],kx+12*q,ky);kx+=122*q});
    function Y(v){return pad.top+((mm.hi-v)/(mm.hi-mm.lo))*(h-pad.top-pad.bottom)}function drawSeries(field,color){g.save();g.lineWidth=2.1*q;g.lineCap='round';g.lineJoin='round';g.setLineDash([8*q,5*q]);g.strokeStyle=color;g.shadowColor=color;g.shadowBlur=6*q;g.beginPath();var started=false;rows.forEach(function(row){var v=Number(row[field]);if(isNaN(v))return;var x=xFor(row,t0,t1,w,pad),y=Y(v);if(started)g.lineTo(x,y);else{g.moveTo(x,y);started=true}});g.stroke();g.restore()}
    drawSeries('forecastHigh','#ffcc00');drawSeries('forecastAverage','#00ffff');drawSeries('forecastLow','#ff3333');
    rows.forEach(function(row){if(row.actualHigh==null&&row.actualAverage==null&&row.actualLow==null)return;var x=xFor(row,t0,t1,w,pad);g.save();g.setLineDash([]);[['actualHigh','#ffcc00'],['actualAverage','#00ffff'],['actualLow','#ff3333']].forEach(function(pair){var v=Number(row[pair[0]]);if(isNaN(v))return;g.fillStyle=pair[1];g.shadowColor=pair[1];g.shadowBlur=6*q;g.beginPath();g.arc(x,Y(v),4.5*q,0,Math.PI*2);g.fill()});g.restore()});
    var hi=rows.reduce(function(a,b){return !a||Number(b.forecastHigh)>Number(a.forecastHigh)?b:a},null),lo=rows.reduce(function(a,b){return !a||Number(b.forecastLow)<Number(a.forecastLow)?b:a},null),avg=rows.length?rows.reduce(function(s,r){return s+Number(r.forecastAverage)},0)/rows.length:0;if(showAnnotations&&hi&&lo){var hx=xFor(hi,t0,t1,w,pad),lx=xFor(lo,t0,t1,w,pad);drawBox(g,q,hx<w/2?hx+14*q:hx-14*q,Math.max(pad.top+52*q,Y(hi.forecastHigh)-20*q),hx<w/2?'left':'right','FORECAST HIGH',hi.forecastHigh,niceDate(hi.date));drawBox(g,q,lx<w/2?lx+14*q:lx-14*q,Math.min(h-pad.bottom-22*q,Y(lo.forecastLow)+52*q),lx<w/2?'left':'right','FORECAST LOW',lo.forecastLow,niceDate(lo.date))}
    var yb=h-98*q,bh=82*q,x=pad.left,bw=w-pad.left-pad.right;g.save();g.fillStyle='rgba(5,7,12,.82)';g.strokeStyle='rgba(0,255,255,.35)';g.beginPath();g.roundRect(x,yb,bw,bh,8*q);g.fill();g.stroke();g.fillStyle='#f5f7fb';g.font='900 '+8.5*q+'px Courier New';g.textAlign='center';var cx=x+bw/2;g.fillText('FORECAST HIGH  '+pence(hi&&hi.forecastHigh)+'p/kWh   £'+fmt(hi&&hi.forecastHigh,2)+'/MWh   '+niceDate(hi&&hi.date),cx,yb+20*q);g.fillText('FORECAST AVG   '+pence(avg)+'p/kWh   £'+fmt(avg,2)+'/MWh   7 day layer',cx,yb+44*q);g.fillText('FORECAST LOW   '+pence(lo&&lo.forecastLow)+'p/kWh   £'+fmt(lo&&lo.forecastLow,2)+'/MWh   '+niceDate(lo&&lo.date),cx,yb+68*q);g.restore();var note=document.getElementById('price-history-forecast-note');if(note)note.textContent=result.method||''}
  function redraw(){if(last)render(last)}
  function setAnnotations(v){showAnnotations=!!v;if(last)render(last)}
  return{render:render,redraw:redraw,setAnnotations:setAnnotations};
})();