#!/usr/bin/env python3
"""
Generate the V6 Architectural Integrity Protocol.

This is a non destructive guardrail generator. It reads the V5 V6 comparison
report if available and writes a standing protocol into the V6 folder.

Output:
uk_energy_tracking_v6/V6_ARCHITECTURAL_INTEGRITY_PROTOCOL.md
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
V6 = ROOT / "uk_energy_tracking_v6"
COMPARE_REPORT = V6 / "V5_V6_COMPARISON_REPORT.md"
OUTPUT = V6 / "V6_ARCHITECTURAL_INTEGRITY_PROTOCOL.md"

DOCS = [
    "AI_START_HERE.md",
    "ARCHITECTURE.md",
    "PHILOSOPHY.md",
    "LAUNCH_FREEZE.md",
    "OPERATOR_MANUAL_V1.md",
    "WORKFLOW_REGISTRY.md",
    "GRIDBOT_FEATURE_INSTALL_INSTRUCTIONS.md",
    "uk_energy_tracking_v5/README.md",
    "uk_energy_tracking_v5/AI_RELOAD_INSTRUCTIONS.md",
    "uk_energy_tracking_v6/V5_V6_COMPARISON_REPORT.md",
    "uk_energy_tracking_v6/V6_ARCHITECTURAL_INTEGRITY_PROTOCOL.md",
]


def exists(path: str) -> str:
    return "yes" if (ROOT / path).exists() else "no"


def extract_compare_summary() -> list[str]:
    if not COMPARE_REPORT.exists():
        return [
            "Comparison report status: not yet present.",
            "Required action: run `Compare UK Energy Tracking V5 and V6` before any V6 repair workflow is designed.",
        ]
    text = COMPARE_REPORT.read_text(encoding="utf-8", errors="replace")
    wanted = [
        "## Critical chart contract checks",
        "## DOM id parity",
        "## Page load order",
        "## Data file comparison",
        "## Initial interpretation rules",
    ]
    lines = text.splitlines()
    out: list[str] = []
    for heading in wanted:
        if heading not in text:
            out.append(f"Missing section in comparison report: {heading}")
            continue
        idx = lines.index(heading)
        chunk = []
        for line in lines[idx:idx + 45]:
            if line.startswith("## ") and line != heading and chunk:
                break
            chunk.append(line)
        out.append("\n".join(chunk))
    return out


def main() -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    compare_status = "present" if COMPARE_REPORT.exists() else "missing"

    lines: list[str] = []
    lines.append("# V6 Architectural Integrity Protocol")
    lines.append("")
    lines.append(f"Generated UTC: `{now}`")
    lines.append("Status: mandatory pre change guardrail for `uk_energy_tracking_v6`")
    lines.append("Scope: UK Energy Tracking V6 only")
    lines.append("Comparison report: `" + compare_status + "`")
    lines.append("")
    lines.append("## 1. Purpose")
    lines.append("")
    lines.append("This file exists to prevent AI or human haste from overwriting working dependencies in V6. It must be read before any new V6 change is proposed, scripted, reviewed or executed.")
    lines.append("")
    lines.append("V6 is a modular rewrite of a working reference. Modularisation is not proof of correctness. The working behaviour must be compared against V5 before changes are made.")
    lines.append("")
    lines.append("## 2. Binding operating rule")
    lines.append("")
    lines.append("All V6 changes, however small or large, must be made through a named GitHub workflow or a reviewed workflow generated by a script. Direct ad hoc editing of V6 application files is not allowed during repair work.")
    lines.append("")
    lines.append("The sequence is:")
    lines.append("")
    lines.append("1. Read this protocol.")
    lines.append("2. Read `uk_energy_tracking_v6/V5_V6_COMPARISON_REPORT.md`.")
    lines.append("3. Identify one defect or one controlled repair only.")
    lines.append("4. Create a Python repair script or deterministic patch script.")
    lines.append("5. Create a matching GitHub Actions workflow.")
    lines.append("6. Workflow runs the script and writes a report into `uk_energy_tracking_v6/`.")
    lines.append("7. Workflow commits only the intended files and the repair report.")
    lines.append("8. Maintainer tests the live page.")
    lines.append("9. No second feature is added until the first is accepted or reverted.")
    lines.append("")
    lines.append("## 3. Required documents to read")
    lines.append("")
    lines.append("| Document | Exists | Purpose |")
    lines.append("|---|---:|---|")
    purposes = {
        "AI_START_HERE.md": "AI starting rules and repo orientation",
        "ARCHITECTURE.md": "global architecture and doctrine",
        "PHILOSOPHY.md": "platform intent and design philosophy",
        "LAUNCH_FREEZE.md": "pre launch freeze rule",
        "OPERATOR_MANUAL_V1.md": "operating doctrine and licence guidance",
        "WORKFLOW_REGISTRY.md": "workflow preservation rule",
        "GRIDBOT_FEATURE_INSTALL_INSTRUCTIONS.md": "controlled workflow method",
        "uk_energy_tracking_v5/README.md": "V5 purpose and reference twin rules",
        "uk_energy_tracking_v5/AI_RELOAD_INSTRUCTIONS.md": "V5 recovery and AI rules",
        "uk_energy_tracking_v6/V5_V6_COMPARISON_REPORT.md": "specific V5 versus V6 defect map",
        "uk_energy_tracking_v6/V6_ARCHITECTURAL_INTEGRITY_PROTOCOL.md": "this guardrail file",
    }
    for doc in DOCS:
        lines.append(f"| `{doc}` | {exists(doc)} | {purposes.get(doc, '')} |")
    lines.append("")
    lines.append("## 4. Non negotiable V6 chart contract")
    lines.append("")
    lines.append("The raw chart must show published data only. Experimental forecast layers must not contaminate the raw chart.")
    lines.append("")
    lines.append("The current raw chart contract is:")
    lines.append("")
    lines.append("1. 12 hour, 1 day, 7 day, 30 day, 3 month and 6 month views use full half hourly settlement data.")
    lines.append("2. 12 month, 5 year and 10 year views use the daily aggregate file and must preserve daily high, average and low.")
    lines.append("3. V5 is the behavioural reference unless the comparison report proves a V6 difference is intentional.")
    lines.append("4. High, average and low values must not be hidden for visual neatness.")
    lines.append("5. Full screen, period arrows, mobile portrait, mobile landscape and desktop must be checked after every chart repair.")
    lines.append("6. Elexon source fields and generated daily aggregate values must remain traceable.")
    lines.append("")
    lines.append("## 5. Forbidden repair behaviour")
    lines.append("")
    lines.append("Do not:")
    lines.append("")
    lines.append("1. Rewrite whole V6 files by hand when a smaller deterministic patch is possible.")
    lines.append("2. Add a forecast, annotation or new UI feature while the raw V6 chart is still not at V5 parity.")
    lines.append("3. Delete V5, V4 or any stable reference app.")
    lines.append("4. Move shared datasets or change data paths without a workflow and explicit approval.")
    lines.append("5. Hide data truth to make the chart look cleaner.")
    lines.append("6. Patch multiple unrelated defects in one workflow.")
    lines.append("7. Trust screenshots alone without comparing source files and data outputs.")
    lines.append("")
    lines.append("## 6. Required repair workflow shape")
    lines.append("")
    lines.append("Every V6 repair must use this structure:")
    lines.append("")
    lines.append("```text")
    lines.append("scripts/repair_v6_<short_name>.py")
    lines.append(".github/workflows/repair_v6_<short_name>.yml")
    lines.append("uk_energy_tracking_v6/V6_REPAIR_<SHORT_NAME>_REPORT.md")
    lines.append("```")
    lines.append("")
    lines.append("The Python script must:")
    lines.append("")
    lines.append("1. Read this protocol.")
    lines.append("2. Read the V5 V6 comparison report.")
    lines.append("3. Read the target file or files.")
    lines.append("4. Assert expected old text or expected structure before editing.")
    lines.append("5. Make the smallest necessary change.")
    lines.append("6. Assert expected new text or structure after editing.")
    lines.append("7. Write a repair report into the V6 folder.")
    lines.append("")
    lines.append("The workflow must:")
    lines.append("")
    lines.append("1. Run the Python repair script.")
    lines.append("2. Commit only the target files and the repair report.")
    lines.append("3. Use a clear commit message.")
    lines.append("4. Avoid broad `git add .` unless the script itself generated a manifest of touched files.")
    lines.append("")
    lines.append("## 7. Comparison report extracts")
    lines.append("")
    for block in extract_compare_summary():
        lines.append("```text")
        lines.append(block)
        lines.append("```")
        lines.append("")
    lines.append("## 8. Approval sentence")
    lines.append("")
    lines.append("No V6 app change should proceed unless the maintainer can say:")
    lines.append("")
    lines.append("> This repair has been compared against V5, is limited to one defect, is workflow driven, writes a V6 repair report and preserves the raw published data chart.")
    lines.append("")
    lines.append("## 9. Final rule")
    lines.append("")
    lines.append("If there is doubt, stop and regenerate the comparison report. Do not improvise inside V6.")
    lines.append("")

    OUTPUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
