#!/usr/bin/env python3
"""
GlobalGrid2050 repository size tracker.

Creates a root level Markdown report and CSV history using GitHub repository
metadata plus optional local checkout measurements when run inside GitHub
Actions.

This script is deliberately non destructive. It does not move data, delete files,
rewrite history, migrate to Git LFS or alter application paths.
"""

from __future__ import annotations

import csv
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

ROOT = Path(__file__).resolve().parent.parent
REPORT_FILE = ROOT / "REPOSITORY_SIZE_REPORT.md"
HISTORY_FILE = ROOT / "repository_size_history.csv"

REPO_FULL_NAME = os.getenv("GITHUB_REPOSITORY", "Ventusltd/globalgrid2050")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN") or os.getenv("GH_TOKEN") or os.getenv("GRIDBOT_PAT")

PRACTICAL_WATCH_MB = 500
PRACTICAL_PLAN_MB = 1000
HARD_SINGLE_FILE_WARNING_MB = 100


def utc_now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def mb_from_kb(kb: float | int | None) -> float | None:
    if kb is None:
        return None
    return round(float(kb) / 1024.0, 2)


def run_command(args: list[str]) -> str | None:
    try:
        completed = subprocess.run(args, cwd=ROOT, check=True, text=True, capture_output=True)
    except Exception:
        return None
    return completed.stdout.strip()


def local_du_kb(path: Path) -> int | None:
    text = run_command(["du", "-sk", str(path)])
    if not text:
        return None
    try:
        return int(text.split()[0])
    except (ValueError, IndexError):
        return None


def git_objects_summary() -> dict[str, str]:
    text = run_command(["git", "count-objects", "-vH"])
    if not text:
        return {}
    out: dict[str, str] = {}
    for line in text.splitlines():
        if ":" not in line:
            continue
        key, value = line.split(":", 1)
        out[key.strip()] = value.strip()
    return out


def fetch_github_repo_metadata() -> dict[str, object]:
    url = f"https://api.github.com/repos/{REPO_FULL_NAME}"
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "GlobalGrid2050 repository size tracker",
    }
    if GITHUB_TOKEN:
        headers["Authorization"] = f"Bearer {GITHUB_TOKEN}"
    request = Request(url, headers=headers)
    try:
        with urlopen(request, timeout=30) as response:
            return json.loads(response.read().decode("utf-8"))
    except HTTPError as exc:
        raise SystemExit(f"GitHub API HTTP error {exc.code}: {exc.reason}") from exc
    except URLError as exc:
        raise SystemExit(f"GitHub API error: {exc.reason}") from exc


def read_history() -> list[dict[str, str]]:
    if not HISTORY_FILE.exists():
        return []
    with HISTORY_FILE.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def append_history(row: dict[str, object]) -> list[dict[str, str]]:
    fields = [
        "checked_utc",
        "repository",
        "github_size_kb",
        "github_size_mb",
        "working_tree_kb",
        "working_tree_mb",
        "git_size_pack",
        "git_size_garbage",
        "watch_status",
    ]
    existing = read_history()
    new_row = {field: str(row.get(field, "")) for field in fields}
    if existing and existing[-1].get("github_size_kb") == new_row["github_size_kb"]:
        existing[-1] = new_row
    else:
        existing.append(new_row)
    with HISTORY_FILE.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(existing)
    return existing


def status_for_size(size_mb: float | None) -> str:
    if size_mb is None:
        return "unknown"
    if size_mb >= PRACTICAL_PLAN_MB:
        return "plan data repository or paid storage now"
    if size_mb >= PRACTICAL_WATCH_MB:
        return "watch closely and design data split"
    return "normal"


def write_report(row: dict[str, object], history: list[dict[str, str]]) -> None:
    github_mb = row.get("github_size_mb")
    working_mb = row.get("working_tree_mb")
    status = row.get("watch_status")
    history_tail = history[-12:]

    lines = [
        "# GlobalGrid2050 Repository Size Report",
        "",
        "This report is generated by `scripts/track_repository_size.py` and can be updated manually or monthly by GitHub Actions.",
        "",
        "The purpose is to monitor repository growth without moving files, deleting history or splitting the data layer before there is a real need.",
        "",
        "## Latest measurement",
        "",
        f"Checked UTC: `{row.get('checked_utc')}`",
        f"Repository: `{row.get('repository')}`",
        f"GitHub reported size: `{row.get('github_size_kb')} KB` / `{github_mb} MB`",
        f"Local checkout size during workflow: `{row.get('working_tree_kb') or 'not measured'} KB` / `{working_mb if working_mb is not None else 'not measured'} MB`",
        f"Git object pack size: `{row.get('git_size_pack') or 'not measured'}`",
        f"Git garbage size: `{row.get('git_size_garbage') or 'not measured'}`",
        f"Watch status: `{status}`",
        "",
        "## Interpretation",
        "",
        "GitHub's reported repository size is the primary governance number for this project.",
        "",
        "A zipped download, a local checkout and a full clone can show different sizes because CSV and GeoJSON compress heavily and local clones include working files plus Git history.",
        "",
        "Historical data is not treated as junk. It is intentionally retained when it supports traceability, energy analysis or platform intelligence.",
        "",
        "Junk means local generated files such as Python cache, operating system files, temporary build folders or local environment files. Those are controlled by `.gitignore`.",
        "",
        "## Watch thresholds",
        "",
        f"Normal zone: below `{PRACTICAL_WATCH_MB} MB` reported by GitHub.",
        f"Planning zone: `{PRACTICAL_WATCH_MB} MB` to `{PRACTICAL_PLAN_MB} MB` reported by GitHub.",
        f"Action zone: around `{PRACTICAL_PLAN_MB} MB` reported by GitHub, or earlier if clone and workflow performance becomes poor.",
        f"Single file warning zone: around `{HARD_SINGLE_FILE_WARNING_MB} MB` for any individual file.",
        "",
        "## Future expansion options",
        "",
        "Do not execute these before launch unless explicitly approved.",
        "",
        "1. Keep the main repository as the website and application repository.",
        "2. Create a separate `globalgrid2050-data` repository only when repository size or workflow performance justifies it.",
        "3. Move high frequency CSV and GeoJSON history to the data repository only after dual path testing.",
        "4. Keep old data paths in the main repository during transition until live pages are proven stable.",
        "5. Consider Git LFS, GitHub Releases or commercial object storage only when the data layer requires it.",
        "",
        "## Last 12 measurements",
        "",
        "| Checked UTC | GitHub MB | Working tree MB | Status |",
        "|---|---:|---:|---|",
    ]
    for item in history_tail:
        lines.append(
            f"| {item.get('checked_utc', '')} | {item.get('github_size_mb', '')} | {item.get('working_tree_mb', '') or 'not measured'} | {item.get('watch_status', '')} |"
        )
    lines.extend([
        "",
        "## Launch freeze rule",
        "",
        "Until launch is complete, repository size monitoring is informational only. Do not move datasets, delete versions, split repositories or rewrite Git history without explicit human approval.",
        "",
    ])
    REPORT_FILE.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    metadata = fetch_github_repo_metadata()
    github_size_kb = metadata.get("size")
    github_size_mb = mb_from_kb(github_size_kb if isinstance(github_size_kb, (int, float)) else None)
    working_tree_kb = local_du_kb(ROOT)
    working_tree_mb = mb_from_kb(working_tree_kb)
    git_summary = git_objects_summary()

    row: dict[str, object] = {
        "checked_utc": utc_now(),
        "repository": REPO_FULL_NAME,
        "github_size_kb": github_size_kb,
        "github_size_mb": github_size_mb,
        "working_tree_kb": working_tree_kb or "",
        "working_tree_mb": working_tree_mb if working_tree_mb is not None else "",
        "git_size_pack": git_summary.get("size-pack", ""),
        "git_size_garbage": git_summary.get("garbage", ""),
        "watch_status": status_for_size(github_size_mb),
    }
    history = append_history(row)
    write_report(row, history)
    print(f"Repository size report updated: {REPORT_FILE.name}")
    print(f"GitHub reported size: {github_size_mb} MB")
    print(f"Watch status: {row['watch_status']}")


if __name__ == "__main__":
    main()
