window.V6ControlSolarDailyMwhChart=(function(){
  var cache=null;
  function cfg(){return window.V6GenerationHistoryConfig||{}}
  function get(id){return document.getElementById(id)}
  function loadSolarDaily(){if(cache)return cache;var url=cfg().solarDaily||'/uk_energy_tracking_v6_2/generation_history/pvlive_solar_daily_browser.json';cache=fetch(url+'?t='+Date.now(),{cache:'no-store'}).then(function(r){return r.ok?r.json():{rows:[]}}).then(function(d){return d.rows||[]}).catch(function(){return[]});return cache}
  function periodDays(p){return{'30d':30,'3m':92,'6m':183,'12m':366,'5y':1827,'10y':3653}[p]||366}
  function niceDate(v){var d=v instanceof Date?v:new Date(String(v));return isNaN(d.getTime())?'—':d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'})}
  function years(rows){var out={};rows.forEach(function(r){if(r&&r.date)out[String(r.date).slice(0,4)]=true});return Object.keys(out).sort()}
  function setDefaultControls(rows){var yEl=get('solar-daily-mwh-year'),sEl=get('solar-daily-mwh-start');if(!yEl||!sEl||yEl.dataset.ready==='1')return;var ys=years(rows);yEl.innerHTML='';ys.forEach(function(y){var o=document.createElement('option');o.value=y;o.textContent=y;yEl.appendChild(o)});var latest=ys[ys.length-1]||String(new Date().getUTCFullYear());yEl.value=latest;sEl.value=latest+'-01-01';yEl.dataset.ready='1'}
  function selectedWindow(rows){var yEl=get('solar-daily-mwh-year'),sEl=get('solar-daily-mwh-start'),pEl=get('solar-daily-mwh-period');setDefaultControls(rows);var period=pEl?pEl.value:'12m';var startText=sEl&&sEl.value?sEl.value:((yEl&&yEl.value?yEl.value:String(new Date().getUTCFullYear()))+'-01-01');var start=new Date(startText+'T00:00:00Z');var end;if(period==='all'){var valid=rows.filter(function(r){return r&&r.date});start=new Date((valid[0]?valid[0].date:startText)+'T00:00:00Z');end=new Date((valid[valid.length-1]?valid[valid.length-1].date:startText)+'T23:59:59Z')}else{end=new Date(start.getTime()+periodDays(period)*86400000-1000)}return{start:start,end:end,period:period}}
  function update(){var panel=get('solar-daily-mwh-panel'),canvas=get('solar-daily-mwh-canvas'),status=get('solar-daily-mwh-status'),techEl=get('solar-daily-mwh-technology');if(!panel||!canvas||!status||!window.V6RenderSolarDailyMwhChart)return;var tech=techEl?techEl.value:'Solar';panel.style.display='block';if(tech!=='Solar'){status.textContent='Only Solar is enabled until other daily MWh data is audited.';return}loadSolarDaily().then(function(all){setDefaultControls(all);var meta=selectedWindow(all);var rows=all.filter(function(r){var t=new Date(r.date+'T12:00:00Z');return t>=meta.start&&t<=meta.end&&r.mwh!=null&&!isNaN(Number(r.mwh))});status.textContent='SOLAR DAILY MWH · '+rows.length+' RECORDS · '+niceDate(meta.start)+' TO '+niceDate(meta.end)+' · SHEFFIELD SOLAR PVLIVE STORED MWH';window.V6RenderSolarDailyMwhChart.render(canvas,{rows:rows,start:meta.start,end:meta.end,period:meta.period})})}
  function boot(){loadSolarDaily().then(function(rows){setDefaultControls(rows);update()});['solar-daily-mwh-technology','solar-daily-mwh-year','solar-daily-mwh-start','solar-daily-mwh-period'].forEach(function(id){var el=get(id);if(el)el.addEventListener('change',function(){if(id==='solar-daily-mwh-year'){var s=get('solar-daily-mwh-start');if(s&&el.value)s.value=el.value+'-01-01'}setTimeout(update,60)})});window.addEventListener('resize',function(){setTimeout(update,80)});setTimeout(update,300);setTimeout(update,1200)}
  return{boot:boot,update:update};
})();
document.addEventListener('DOMContentLoaded',function(){if(window.V6ControlSolarDailyMwhChart)window.V6ControlSolarDailyMwhChart.boot()});

// Solar daily MWh fullscreen and period interaction bridge
(function(){
  function get(id){return document.getElementById(id)}
  function syncFullPeriod(){var p=get('solar-daily-mwh-period'),fp=get('solar-daily-mwh-fullscreen-period-select');if(p&&fp&&fp.value!==p.value)fp.value=p.value}
  function setPeriod(value){var p=get('solar-daily-mwh-period');if(p)p.value=value;syncFullPeriod();if(window.V6ControlSolarDailyMwhChart)window.V6ControlSolarDailyMwhChart.update()}
  function nudgePeriod(dir){var s=get('solar-daily-mwh-start'),p=get('solar-daily-mwh-period');if(!s||!p)return;var days={'30d':30,'3m':92,'6m':183,'12m':366,'5y':1827,'10y':3653}[p.value]||366;var d=s.value?new Date(s.value+'T00:00:00Z'):new Date();d=new Date(d.getTime()+dir*days*86400000);s.value=d.toISOString().slice(0,10);var y=get('solar-daily-mwh-year');if(y)y.value=String(d.getUTCFullYear());if(window.V6ControlSolarDailyMwhChart)window.V6ControlSolarDailyMwhChart.update()}
  function openFull(){var o=get('solar-daily-mwh-fullscreen-overlay');if(!o)return;syncFullPeriod();o.classList.add('open');document.documentElement.classList.add('v5-chart-open');document.body.classList.add('v5-chart-open');setTimeout(function(){if(window.V6RenderSolarDailyMwhChart&&window.V6RenderSolarDailyMwhChart.redrawFullscreen)window.V6RenderSolarDailyMwhChart.redrawFullscreen()},100)}
  function closeFull(){var o=get('solar-daily-mwh-fullscreen-overlay');if(!o)return;o.classList.remove('open');document.documentElement.classList.remove('v5-chart-open');document.body.classList.remove('v5-chart-open')}
  function bind(){var btn=get('solar-daily-mwh-fullscreen-btn'),close=get('solar-daily-mwh-fullscreen-close'),fp=get('solar-daily-mwh-fullscreen-period-select'),back=get('solar-daily-mwh-fullscreen-period-back'),forward=get('solar-daily-mwh-fullscreen-period-forward');if(btn&&!btn.dataset.bound){btn.dataset.bound='1';btn.addEventListener('click',openFull)}if(close&&!close.dataset.bound){close.dataset.bound='1';close.addEventListener('click',closeFull)}if(fp&&!fp.dataset.bound){fp.dataset.bound='1';fp.addEventListener('change',function(){setPeriod(fp.value)})}if(back&&!back.dataset.bound){back.dataset.bound='1';back.addEventListener('click',function(){nudgePeriod(-1)})}if(forward&&!forward.dataset.bound){forward.dataset.bound='1';forward.addEventListener('click',function(){nudgePeriod(1)})}}
  document.addEventListener('DOMContentLoaded',function(){setTimeout(bind,200);setTimeout(bind,1200)});
})();
