/* build.mjs — the nest's manifest, generated from the directory, never typed.
 *
 * WHY THIS EXISTS. The old front door at testcode/index.html was 184 bytes and
 * named two surfaces out of ninety-six, the newest of them eleven days old. It
 * was hand-typed, so it went stale the moment the next surface landed. Every
 * stale map in this estate has the same cause: an artefact generated by a run,
 * and no run triggered by publication. This file is the run. It reads the
 * directory it sits beside and writes what is actually there.
 *
 * WHAT IT EMITS. surfaces.json: one record per timestamped surface directory,
 * carrying its key, its title read from its own README or <title>, the files it
 * holds and the bytes they weigh. Nothing is invented; a surface with no README
 * and no title says so rather than being given a name.
 *
 * Run: node build.mjs   (from this directory)
 */
import fs from 'node:fs';
import path from 'node:path';

const HERE = path.dirname(new URL(import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, '$1'));
const ROOT = path.resolve(HERE, '..');            /* testcode/ */
const TS = /^(\d{12}|\d{10}|\d{14})$/;            /* the estate's three stamp widths */

/* A stamp is YYYYMMDDHHMM, sometimes YYYYMMDDHHMMSS, sometimes YYYYMMDDHH.
   Read only what is certainly there: the date, and the time when present. */
function readStamp(name) {
  const y = name.slice(0, 4), m = name.slice(4, 6), d = name.slice(6, 8);
  const hh = name.slice(8, 10) || null, mm = name.slice(10, 12) || null;
  return { date: `${y}-${m}-${d}`, time: hh && mm ? `${hh}:${mm}` : null };
}

/* The surface's own name for itself, in order of authority: the first heading of
   its README, then the <title> of its index.html, then nothing. Never a guess. */
function readTitle(dir) {
  const rd = path.join(dir, 'README.md');
  if (fs.existsSync(rd)) {
    const h = fs.readFileSync(rd, 'utf8').split(/\r?\n/).find(l => l.startsWith('# '));
    if (h) return { title: h.replace(/^#\s*/, '').trim(), from: 'README.md' };
  }
  const ix = path.join(dir, 'index.html');
  if (fs.existsSync(ix)) {
    const m = fs.readFileSync(ix, 'utf8').match(/<title>([^<]+)<\/title>/i);
    if (m) return { title: m[1].trim(), from: 'index.html' };
  }
  return { title: null, from: null };
}

function walk(dir) {
  let files = 0, bytes = 0;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.name === 'node_modules' || e.name === '.git') continue;
    const p = path.join(dir, e.name);
    if (e.isDirectory()) { const s = walk(p); files += s.files; bytes += s.bytes; }
    else { files++; bytes += fs.statSync(p).size; }
  }
  return { files, bytes };
}

const names = fs.readdirSync(ROOT, { withFileTypes: true })
  .filter(e => e.isDirectory() && TS.test(e.name))
  .map(e => e.name)
  .sort();

const surfaces = names.map((name, i) => {
  const dir = path.join(ROOT, name);
  const { title, from } = readTitle(dir);
  const { files, bytes } = walk(dir);
  return {
    key: i + 1,                 /* the nest's own ordinal: 1..n, in issue order */
    stamp: name,
    ...readStamp(name),
    title, title_from: from,
    files, bytes,
    has_readme: fs.existsSync(path.join(dir, 'README.md')),
    has_proof: fs.existsSync(path.join(dir, 'proof')),
    entry: fs.existsSync(path.join(dir, 'index.html')) ? `${name}/` : null,
  };
});

const out = {
  generated_utc: new Date().toISOString(),
  built_from: 'globalgrid2050/testcode',
  surfaces: surfaces.length,
  named: surfaces.filter(s => s.title).length,
  openable: surfaces.filter(s => s.entry).length,
  total_files: surfaces.reduce((a, s) => a + s.files, 0),
  total_bytes: surfaces.reduce((a, s) => a + s.bytes, 0),
  law: 'r = sqrt(key) · theta = key × 2.39996…  (the golden angle)',
  list: surfaces,
};

fs.writeFileSync(path.join(HERE, 'surfaces.json'), JSON.stringify(out, null, 1));
console.log(`surfaces ${out.surfaces} · named ${out.named} · openable ${out.openable} · files ${out.total_files} · ${(out.total_bytes / 1048576).toFixed(1)} MB`);
