/* nest.mjs — the front door to every test code surface in the estate.
 *
 * WHAT THIS IS. testcode/ holds the gallery: ninety-seven dated surfaces, each a
 * self-contained page. Its front door was 184 bytes of hand-typed HTML naming two
 * of them, the newest eleven days old. This draws all of them, from a manifest
 * generated by build.mjs out of the directory itself, so it cannot name a surface
 * that is not there or omit one that is.
 *
 * THE LAW, TAKEN UNCHANGED FROM testcode/202609151339. A surface's position is a
 * pure function of its own issue number and of nothing else:
 *
 *     r = sqrt(key)        theta = key x 2.39996...      (the golden angle)
 *
 * The Line Wafer places 250,174 lines that way. The Nest places the surfaces that
 * contain them the same way, one level up: the die above the cells. Nothing about
 * a position is stored, fetched or remembered, so surface 98 already has a place
 * and the ninety-eighth build will not move the other ninety-seven.
 *
 * WHY A CPU AND NOT A GALAXY. A die is logic cells plus the routing between them,
 * read at whatever zoom the reader needs: die, block, cell. That is the same shape
 * as an estate of surfaces holding families holding lines, so the navigation is
 * borrowed from what the code already is rather than from a picture it resembles.
 *
 * WHAT IS NOT CLAIMED. Proximity on this die is not similarity. Two surfaces
 * adjacent here were issued near each other in time, nothing more. The golden
 * angle spreads them evenly; it does not cluster what belongs together, and no
 * edge is drawn between surfaces because none has been established.
 *
 * COST. One fetch of surfaces.json (28 KB) and no other network use at any zoom.
 * Positions are arithmetic, so they weigh nothing and cannot go stale.
 */

const TAU = Math.PI * 2;
const GOLDEN = Math.PI * (3 - Math.sqrt(5));      /* 2.39996... rad */

const stage = document.getElementById('stage');
const ctx = stage.getContext('2d', { alpha: false });
const countEl = document.getElementById('count');
const footEl = document.getElementById('foot');
const panel = document.getElementById('panel');
const panelBody = document.getElementById('panelbody');

let data = null, pts = [], focus = null, dpr = 1;

/* Position is arithmetic on the key. Never stored, never fetched. */
const place = (key) => ({ r: Math.sqrt(key), a: key * GOLDEN });

const fmtBytes = (b) =>
  b >= 1048576 ? (b / 1048576).toFixed(1) + ' MB'
    : b >= 1024 ? (b / 1024).toFixed(0) + ' KB' : b + ' B';

function layout() {
  dpr = Math.min(devicePixelRatio || 1, 2);
  stage.width = Math.floor(innerWidth * dpr);
  stage.height = Math.floor(innerHeight * dpr);
  if (!data) return;
  const cx = stage.width / 2, cy = stage.height / 2;
  /* One scale so the outermost surface sits inside the shorter edge with room
     for its label. sqrt(count) is the radius of the whole die. */
  const maxR = Math.sqrt(data.list.length);
  const pad = 42 * dpr;
  const scale = (Math.min(stage.width, stage.height) / 2 - pad) / maxR;
  pts = data.list.map((s) => {
    const p = place(s.key);
    return { s, x: cx + Math.cos(p.a) * p.r * scale, y: cy + Math.sin(p.a) * p.r * scale };
  });
}

/* A surface's weight is its file count on a log scale, so a 4-file page and a
   4,000-file pack are both legible instead of one erasing the other. */
const radiusOf = (s) => (3 + Math.log2(1 + s.files) * 1.15) * dpr;

function draw() {
  ctx.fillStyle = '#0b0d12';
  ctx.fillRect(0, 0, stage.width, stage.height);
  if (!data) return;

  const newest = data.list.length;
  for (const p of pts) {
    const s = p.s;
    const age = s.key / newest;                    /* 0 oldest ... 1 newest */
    const rad = radiusOf(s);

    /* Unopenable surfaces are drawn hollow rather than hidden: the gaps in the
       gallery are part of what the gallery is. */
    if (!s.entry) {
      ctx.strokeStyle = '#3d4761';
      ctx.lineWidth = 1 * dpr;
      ctx.beginPath(); ctx.arc(p.x, p.y, rad, 0, TAU); ctx.stroke();
      continue;
    }
    const r = Math.round(94 + age * 161);
    const g = Math.round(150 + age * 63);
    const b = Math.round(242 - age * 68);
    ctx.fillStyle = 'rgba(' + r + ',' + g + ',' + b + ',' + (0.45 + age * 0.55) + ')';
    ctx.beginPath(); ctx.arc(p.x, p.y, rad, 0, TAU); ctx.fill();
  }

  /* The newest surface is the one the reader almost always wants, so it is named
     on the die rather than requiring a tap to find. */
  const last = pts[pts.length - 1];
  if (last) {
    ctx.strokeStyle = '#ffd54a'; ctx.lineWidth = 1.5 * dpr;
    ctx.beginPath(); ctx.arc(last.x, last.y, radiusOf(last.s) + 5 * dpr, 0, TAU); ctx.stroke();
    ctx.fillStyle = '#ffd54a';
    ctx.font = (11 * dpr) + 'px ui-monospace,monospace';
    const right = last.x > stage.width / 2;
    ctx.textAlign = right ? 'right' : 'left';
    ctx.fillText('newest ' + last.s.stamp,
      last.x + (right ? -1 : 1) * (radiusOf(last.s) + 9 * dpr),
      last.y + 4 * dpr);
  }

  if (focus) {
    const p = pts.find((q) => q.s.key === focus.key);
    if (p) {
      ctx.strokeStyle = '#5ec8f2'; ctx.lineWidth = 1.5 * dpr;
      ctx.beginPath(); ctx.arc(p.x, p.y, radiusOf(p.s) + 8 * dpr, 0, TAU); ctx.stroke();
    }
  }
}

function nearest(mx, my) {
  let best = null, bd = Infinity;
  for (const p of pts) {
    const d = (p.x - mx) * (p.x - mx) + (p.y - my) * (p.y - my);
    if (d < bd) { bd = d; best = p; }
  }
  /* A tap that lands nowhere near a surface opens nothing, rather than opening
     whatever happened to be closest across the whole die. */
  const reach = 34 * dpr;
  return best && bd <= reach * reach ? best : null;
}

function show(s) {
  focus = s;
  const when = s.time ? s.date + ' ' + s.time : s.date;
  panelBody.textContent = '';

  const h = document.createElement('h2');
  h.textContent = s.title || 'no title recorded';
  panelBody.append(h);

  const sub = document.createElement('div');
  sub.className = 'dim';
  sub.textContent = s.stamp + ' · issued ' + when;
  panelBody.append(sub);

  const dl = document.createElement('dl');
  const row = (k, v) => {
    const dt = document.createElement('dt'); dt.textContent = k;
    const dd = document.createElement('dd'); dd.textContent = v;
    dl.append(dt, dd);
  };
  row('files', String(s.files));
  row('weight', fmtBytes(s.bytes));
  row('named by', s.title_from || 'nothing - neither README nor title');
  row('README', s.has_readme ? 'yes' : 'no');
  row('proofs', s.has_proof ? 'proof/' : 'none');
  row('key', s.key + ' of ' + data.list.length);
  panelBody.append(dl);

  const a = document.createElement('a');
  a.id = 'open';
  if (s.entry) {
    a.href = '../' + s.entry;
    a.textContent = 'OPEN SURFACE →';
  } else {
    a.setAttribute('aria-disabled', 'true');
    a.textContent = 'no index.html to open';
  }
  panelBody.append(a);

  panel.hidden = false;
  draw();
}

stage.addEventListener('pointerdown', (e) => {
  const hit = nearest(e.clientX * dpr, e.clientY * dpr);
  if (hit) { show(hit.s); } else { panel.hidden = true; focus = null; draw(); }
});
document.getElementById('close').addEventListener('click', () => {
  panel.hidden = true; focus = null; draw();
});
addEventListener('resize', () => { layout(); draw(); });

fetch('surfaces.json')
  .then((r) => (r.ok ? r.json() : Promise.reject(new Error('HTTP ' + r.status))))
  .then((d) => {
    data = d;
    countEl.textContent =
      d.surfaces + ' surfaces · ' + d.total_files.toLocaleString() +
      ' files · ' + fmtBytes(d.total_bytes);
    countEl.classList.remove('dim');
    /* The manifest states when it was generated, because every stale map in this
       estate was one that did not. */
    footEl.textContent =
      d.law + '  ·  ' + d.named + ' of ' + d.surfaces + ' named, ' +
      d.openable + ' openable  ·  directory read ' + d.generated_utc;
    layout(); draw();
  })
  .catch((err) => {
    countEl.textContent = 'surfaces.json did not load: ' + err.message;
    footEl.textContent = 'Run: node build.mjs from this directory to generate it.';
  });
